/** Only pixel-validated authored sheets are registered; no fake completion. */
export const monsterActionOwners=new Set<string>(["absolute_zero","abyssal","abyssal-map-08","aeon_sovereign","aether_mender","alloy_guard","ancient_treant","armored","armored-map-04","armored-map-05","armored-map-06","armored-map-08","bloom_keeper","brute","brute-map-04","brute-map-06","bulwark","bulwark-map-07","bulwark-map-08","causal_blade","chrono_reaper","chrono_stalker","cloud_gunner","coral_mauler","coral_singer","crawler","crawler-map-01","crawler-map-02","crawler-map-03","crawler-map-04","crawler-map-05","cryo_hunter","crystal_bastion","dune_ripper","elite","epoch_caster","fate_weaver","forge_conductor","forge_overseer","frost_howler","gale_colossus","gear_hound","genesis_eye","glacial_tyrant","jammer","jammer-map-05","jammer-map-06","jammer-map-07","jammer-map-08","leviathan","lunar_husk","machine_god","mirage_oracle","moon_ray","named_dune","named_machine","named_sky","named_time","nova_turret","origin_warden","paradox_shell","phantom","phantom-map-07","phantom-map-08","phase_reaper","plasma_hound","prism_cannon","pulse_turret","ravager","ravager-map-04","reactor_behemoth","relic_golem","repair_weaver","rift_executioner","rift_sovereign","runner","runner-map-02","runner-map-03","runner-map-06","sand_colossus","security_exarch","sky_dominion","sky_guard","sky_lancer","solar_sphinx","sovereign","spore_leaper","sprinter","sprinter-map-03","sprinter-map-04","sprinter-map-07","stellar_plate","storm_wyvern","sun_archer","tempest","thorn_matriarch","tide_skimmer","time_mender","verdant_stalker","void_observer"]);
export const MONSTER_ACTION_FRAMES=3;
export const monsterRegionalAliases:Record<string,string>={"sky_guard-map-09":"sky_guard","sky_lancer-map-09":"sky_lancer","cloud_gunner-map-09":"cloud_gunner","aether_mender-map-09":"aether_mender","named_sky-map-09":"named_sky","storm_wyvern-map-09":"storm_wyvern","sky_dominion-map-09":"sky_dominion","relic_golem-map-10":"relic_golem","dune_ripper-map-10":"dune_ripper","sun_archer-map-10":"sun_archer","mirage_oracle-map-10":"mirage_oracle","named_dune-map-10":"named_dune","sand_colossus-map-10":"sand_colossus","solar_sphinx-map-10":"solar_sphinx","alloy_guard-map-11":"alloy_guard","gear_hound-map-11":"gear_hound","pulse_turret-map-11":"pulse_turret","repair_weaver-map-11":"repair_weaver","named_machine-map-11":"named_machine","forge_overseer-map-11":"forge_overseer","machine_god-map-11":"machine_god","paradox_shell-map-12":"paradox_shell","chrono_stalker-map-12":"chrono_stalker","epoch_caster-map-12":"epoch_caster","time_mender-map-12":"time_mender","named_time-map-12":"named_time","chrono_reaper-map-12":"chrono_reaper","aeon_sovereign-map-12":"aeon_sovereign","crystal_bastion-map-13":"crystal_bastion","tide_skimmer-map-13":"tide_skimmer","prism_cannon-map-13":"prism_cannon","coral_singer-map-13":"coral_singer","lunar_husk-map-14":"lunar_husk","spore_leaper-map-14":"spore_leaper","moon_ray-map-14":"moon_ray","bloom_keeper-map-14":"bloom_keeper","stellar_plate-map-15":"stellar_plate","plasma_hound-map-15":"plasma_hound","nova_turret-map-15":"nova_turret","forge_conductor-map-15":"forge_conductor","origin_warden-map-16":"origin_warden","causal_blade-map-16":"causal_blade","genesis_eye-map-16":"genesis_eye","fate_weaver-map-16":"fate_weaver"};
export function monsterActionOwner(id:string,visualId?:string,artArea=0,regional=false){
 if(regional){
  const owner=`${visualId??id}-map-${String(artArea).padStart(2,'0')}`;
  const canonical=monsterRegionalAliases[owner]??owner;
  return monsterActionOwners.has(canonical)?canonical:undefined;
 }
 if(monsterActionOwners.has(id))return id;
 return visualId&&monsterActionOwners.has(visualId)?visualId:undefined;
}
export function monsterActionPath(owner:string,state:'attack'|'hit'|'death',frame:number){
 return `/assets/generated/monster-actions-v2/${owner}/${state}/frame_${String(frame).padStart(2,'0')}.webp`;
}
