import {campaignStages,stageUnlocked,doctrines,pathExposure} from '../data/campaign';
import {heroes,heroById,heroElementName,elementNames} from '../data/heroes';
import {enemies} from '../data/enemies';
import {combatRoles,dealerFirst,formationSlots,formationRole,formationRoleName,formationComplete,formationSort} from '../data/combatRoles';
import {links,priorityNames} from '../data/strategy';
import {CELL} from '../data/map';
import {combatRange,MELEE_STRIKE_RANGE} from '../data/balance';
import type {SaveData} from '../data/types';
import type {BattleModel,BattleResult} from '../systems/BattleModel';
import {button,combatPortrait} from './components';
export const formationFilter={grade:'all',role:'all'};
const stageOf=(s:SaveData)=>campaignStages.find(v=>v.id===s.campaign!.selected)??campaignStages[0];
const miniMap=(id:string)=>{const s=campaignStages.find(s=>s.id===id)!;return `<svg class="campaign-preview" viewBox="0 0 800 800" aria-label="${s.name} 경로"><rect width="800" height="800" fill="#143747"/>${[s.map,s.alternate].filter(Boolean).map(m=>`<polyline points="${m!.path.map(p=>`${p.x},${p.y}`).join(' ')}" fill="none" stroke="#78acb8" stroke-width="42"/>`).join('')}${s.map.slots.map((p,i)=>`<rect x="${p.x-38}" y="${p.y-38}" width="76" height="76" rx="10" fill="#153e46" stroke="#9df3db" stroke-width="4"/><text x="${p.x}" y="${p.y+10}" text-anchor="middle" fill="white" font-size="28">${i+1}</text>`).join('')}<circle cx="${s.map.path.at(-1)!.x}" cy="${s.map.path.at(-1)!.y}" r="32" fill="#9affe3"/></svg>`;};
export function campaignSelect(s:SaveData){const c=s.campaign!,stage=stageOf(s),r=c.records[stage.id],open=stageUnlocked(stage.id,c.records),regions=[1,2,3];return `<section class="campaign-screen campaign-selection"><h1>균열 연구시설 <small>${Object.keys(c.records).length} / ${campaignStages.length} 클리어</small></h1><div class="stage-layout"><div class="campaign-chapters">${regions.map(region=>`<section class="campaign-chapter region-${region}"><b>REGION ${region}</b><div>${campaignStages.filter(v=>v.id.startsWith(region+'-')).map(v=>button(v.id+(stageUnlocked(v.id,c.records)?'':' 🔒'),'campaign-select',v.id===stage.id?'primary':'ghost','',`data-id="${v.id}" aria-pressed="${v.id===stage.id}"`)).join('')}</div></section>`).join('')}</div><article class="campaign-stage"><h2>${stage.id} · ${stage.name} ${stage.id.endsWith('-4')?'BOSS':''}</h2><p>${stage.mechanic}</p><p>주요 적: ${stage.enemies.map(id=>enemies[id]?.name??id).join(' · ')}</p><p>${stage.waves}웨이브 · 권장 전투력 ${stage.power} · 최대 5명 / 6칸<br>추천 조합: ${stage.recommendation}</p><small>최초 보상 ${stage.reward} C · ${r?'★'.repeat(r.stars)+' / 최고 '+r.time+'초':open?'도전 가능':'이전 스테이지 클리어 필요'}</small><details><summary>경로와 배치 보기</summary>${miniMap(stage.id)}</details>${button('실전 맵에서 배치','campaign-deploy','primary','',open?'':'disabled')}</article></div></section>`;}
export function squadSummary(s:SaveData){const c=s.campaign!,left=[...c.squad];const slots=formationSlots.map(role=>{const i=left.findIndex(id=>formationRole(id)===role),id=i>=0?left.splice(i,1)[0]:'';return id?`<button data-action="campaign-toggle" data-id="${id}" aria-label="${heroById[id].name} 편성 해제"><small>${formationRoleName[role]}</small>${combatPortrait(id)}<span>${heroById[id].name}</span></button>`:`<div class="formation-empty"><small>${formationRoleName[role]}</small><b>+</b></div>`;});return `<div class="squad-strip role-slots">${slots.join('')}</div><small>탱커 1 · 딜러 3 · 저격수 1 ${formationComplete(c.squad)?'✓':'· 빈 포지션을 채워주세요'}</small><div class="active-links">${links.filter(l=>l.ids.every(id=>c.squad.includes(id))).map(l=>l.ids.map(id=>heroById[id].name).join(' + ')).join(' · ')||'활성 조합 없음 · 조합 도움말에서 확인'}</div>`;}
export function campaignFormation(s:SaveData){const c=s.campaign!,stage=stageOf(s),doctrine=doctrines.find(d=>d.id===(c.doctrine??'rapid'))??doctrines[0],owned=heroes.filter(h=>s.heroes[h.id].owned);return `<section class="campaign-screen campaign-formation"><header><h1>${stage.id} · 출전 편성</h1><small>보유 ${owned.length} / ${heroes.length} · 탱커 1, 딜러 3, 저격수 1을 편성하세요.</small></header><div id="squad-summary">${squadSummary(s)}</div><div class="doctrine-options" aria-label="작전 특성">${doctrines.map(d=>button(d.name,'campaign-doctrine',d.id===doctrine.id?'primary':'ghost','',`data-id="${d.id}" aria-pressed="${d.id===doctrine.id}"`)).join('')}</div><small id="doctrine-description">${doctrine.text} · 2·4·6웨이브 종료 자동 강화</small><div class="formation-tools"><label>등급 <select id="campaign-grade">${['all','B','A','S','SR'].map(v=>`<option value="${v}" ${formationFilter.grade===v?'selected':''}>${v==='all'?'전체':v}</option>`).join('')}</select></label><label>포지션 <select id="campaign-role">${[['all','전체'],['tank','탱커'],['dealer','딜러'],['sniper','저격수']].map(([v,n])=>`<option value="${v}" ${formationFilter.role===v?'selected':''}>${n}</option>`).join('')}</select></label>${button('조합','campaign-help','ghost')}${button('연구','campaign-lab','ghost')}</div><div class="campaign-roster">${[...heroes].sort(formationSort).map(h=>{const owned=s.heroes[h.id].owned;return `<button class="shop-card ${c.squad.includes(h.id)?'selected':''} ${owned?'':'locked'}" data-action="campaign-toggle" data-id="${h.id}" data-grade="${h.grade}" data-kind="${combatRoles[h.id].kind}" data-role="${formationRole(h.id)}" aria-pressed="${c.squad.includes(h.id)}" ${owned?'':'disabled'}>${combatPortrait(h.id)}<span><b>${h.name} · ${h.grade}</b><small>${formationRoleName[formationRole(h.id)]} · ${owned?combatRoles[h.id].name:'미획득'}</small></span></button>`;}).join('')}</div><div class="formation-actions">${button('스테이지','stage','ghost')}${button('출전 · 초기 배치','campaign-deploy','primary','',formationComplete(c.squad)&&stageUnlocked(stage.id,c.records)?'':'disabled')}</div></section>`;}
export function filterRoster(){document.querySelectorAll<HTMLElement>('.campaign-roster .shop-card').forEach(el=>{el.hidden=!(formationFilter.grade==='all'||el.dataset.grade===formationFilter.grade)||!(formationFilter.role==='all'||el.dataset.role===formationFilter.role||el.dataset.kind===formationFilter.role);});}
export function formationHelp(s:SaveData){return `<h2>추천 조합</h2>${links.map(l=>`<p>${l.ids.map(id=>heroById[id].name).join(' + ')} ${l.ids.every(id=>s.campaign!.squad.includes(id))?'✓':''}<small>${l.text}</small></p>`).join('')}`;}
export function campaignResearch(s:SaveData){const c=s.campaign!,names:Record<string,string>={...elementNames,burst:'기관총',sniper:'저격',melee:'근접',chain:'연쇄',meteor:'마법',drone:'드론',support:'지원'};return `<h2>영구 연구 · ${s.credits} C</h2><p>속성·역할별 단계당 공격력 +3% · 최대 10단계</p><div class="campaign-research">${Object.keys(names).map(key=>{const lv=c.research[key]??0;return button(`${names[key]} Lv.${lv} · ${100*(lv+1)}C`,'campaign-research','ghost','',`data-id="${key}" ${lv>=10||s.credits<100*(lv+1)?'disabled':''}`);}).join('')}</div>`;}
function campaignPrep(m:BattleModel){const selected=new Set(m.units.map(u=>u.heroId));return `<section id="campaign-prep" class="campaign-prep"><b>실전 배치 <span id="prep-count">0 / ${m.units.length}</span></b><small>탱커 1 · 딜러 3 · 저격수 1 / 요원 선택 → 빈칸 선택</small>${button('추천 배치 자동 적용','campaign-auto-deploy','ghost','deck',formationComplete(m.units.map(u=>u.heroId))?'':'disabled')}<div class="prep-doctrines">${doctrines.map(d=>button(d.name,'campaign-doctrine',d.id===m.doctrine?'primary':'ghost','',`data-id="${d.id}"`)).join('')}</div><details><summary>출전 요원 변경 · ${m.units.length}/5</summary><div class="prep-roster">${[...heroes].sort(formationSort).map(h=>{const owned=m.save.heroes[h.id].owned;return `<button data-action="campaign-prep-toggle" data-id="${h.id}" data-role="${formationRole(h.id)}" class="${selected.has(h.id)?'selected':''} ${owned?'':'locked'}" aria-pressed="${selected.has(h.id)}" ${owned?'':'disabled'}>${combatPortrait(h.id)}<span>${h.name}<small>${formationRoleName[formationRole(h.id)]} · ${h.grade}${owned?'':' · 미획득'}</small></span></button>`;}).join('')}</div></details></section>`;}
export function campaignBattle(m:BattleModel){return `<section class="battle-screen compact-battle campaign-battle"><div class="battle-top compact-top"><b>${m.campaign!.id}</b><b id="wave-number">배치 준비</b><span>CORE <b id="core-hp">100</b></span><div class="hp-track"><i id="core-bar"></i></div>${button('x1','speed','compact','','id="speed-btn"')}${button('Ⅱ','pause','compact','','aria-label="일시정지"')}</div><div class="compact-field"><div class="field-wrap"><div class="field-caption">${m.campaign!.name}<span id="enemy-count"></span></div><div id="phaser-container"></div><div class="field-bottom"><span>오른쪽 입구 → 왼쪽 코어</span><span id="field-time"></span></div></div></div>${campaignPrep(m)}<div id="battle-notice" class="battle-notice"></div><div class="growth-host"><div id="selected-growth" class="selected-growth"></div></div><nav class="compact-actions">${button('배치 후 방어 시작','campaign-start','primary','','id="campaign-start-btn" disabled')}${button('DPS','dps','ghost')}</nav><div id="campaign-reserve" class="campaign-reserve"></div><div id="dps-panel" class="dps-panel"></div><details class="campaign-extra"><summary>조합 · 유물 · 자동 강화</summary><div id="synergy-panel" class="synergy-panel"></div><div id="campaign-growth-log"></div></details></section>`;}
export function campaignUnit(m:BattleModel){const u=m.selectedUnit;if(!u)return `<p>모든 칸에 모든 요원 배치 가능 · FRONT에 저지 요원을 두면 후방이 집중 공격<br>${m.started?'캐릭터별 이동 대기 10초':'2·2 후방과 A 보조 칸을 자유롭게 교체할 수 있습니다.'}</p>`;const r=m.ranking().find(v=>v.uid===u.uid),left=Math.max(0,(u.moveReadyAt??0)-m.time),range=m.stats(u).range,base=Math.max(combatRoles[u.heroId].kind==='melee'&&formationRole(u.heroId)!=='tank'?MELEE_STRIKE_RANGE:0,combatRange(heroById[u.heroId].range)),warning=u.slot>=0&&!pathExposure(m.campaign!,u,range).some(v=>v>0),tank=formationRole(u.heroId)==='tank'&&u.slot===4;return `<div class="growth-identity">${combatPortrait(u.heroId)}<div><b>${heroById[u.heroId].name} · ${formationRoleName[formationRole(u.heroId)]} · ${combatRoles[u.heroId].name}</b><small>HP ${Math.ceil(u.hp)} / ${Math.ceil(u.maxHp)} · ${r?.kills??0}킬 · DPS ${(r?.dps??0).toFixed(1)}</small><small>${u.returnAt?`복귀 ${Math.ceil(u.returnAt-m.time)}초`:left?`이동 ${left.toFixed(1)}초`:'이동 가능'} · 사거리 ${(base/CELL).toFixed(2)} + ${((range-base)/CELL).toFixed(2)}칸</small>${tank?'<small class="tank-active">전방 저지 활성 · 근접 접촉 저지 · 저지 +1 · 후방 화력 집중</small>':''}</div></div>${warning?'<small class="range-warning">현재 위치에서 공격 가능한 경로가 없습니다</small>':''}<div class="growth-buttons">${button('선택 해제','deselect','compact')}${button(priorityNames[u.priority??'auto'],'skill','compact')}</div>`;}
export function campaignResult(r:BattleResult){return `<section class="campaign-screen"><h1>${r.stageId} · ${r.won?'방어 성공':'코어 파괴'}</h1><h2>${'★'.repeat(r.stars??0)}</h2><p>${Math.floor(r.time)}초 · ${r.kills}킬 · ${r.credits}C</p><div class="campaign-results">${r.ranking?.map(u=>`<p>${heroById[u.heroId].name} · ${u.kills}킬 · DPS ${u.dps.toFixed(1)} · 누적 ${Math.round(u.damage)}</p>`).join('')}${r.casualties?.map(u=>`<p>${u.name} · 받은 피해 ${Math.round(u.damage)} · 회복 ${Math.round(u.healing)}</p>`).join('')}</div>${button('스테이지 선택','stage','primary')}${button('실전 배치','campaign-deploy','ghost')}</section>`;}
