import { battleMaps } from "../data/map";
import { heroes, heroById, buildNames, gradeNames, heroElementName } from "../data/heroes";
import {dealerFirst} from "../data/combatRoles";
import type { SaveData } from "../data/types";
import type { BattleResult } from "../systems/BattleModel";
import { button, heroCard, icon, num, portrait, time } from "./components";
export function home(s: SaveData) {
  return `<section class="home-screen">
 <div class="city-scene" aria-hidden="true"><div class="city-grid"></div><div class="rift-ring"></div><div class="city-buildings">${Array.from({ length: 18 }, (_, i) => `<i style="--h:${22 + ((i * 29) % 61)}%;--w:${25 + ((i * 17) % 35)}px"></i>`).join("")}</div><div class="ground-grid"></div></div>
 <div class="hero-art"><span class="orbit one"></span><span class="orbit two"></span>${portrait("sera", "featured")}<div class="character-caption"><span>OPERATOR / 05</span><b>세라 <small>SERA</small></b><p>“지휘관, 사선은 제가 확보할게요.”</p></div></div>
 <div class="home-copy"><span class="eyebrow"><i class="live-dot"></i> RIFT RESPONSE DIVISION</span><h1>BEYOND<br>THE <em>RIFT.</em></h1><p class="home-subtitle">균열 너머의 위협.<br>당신만의 작전으로 돌파하세요.</p><div class="chapter-label"><span>CHAPTER 01</span><b>청록 연구시설의 균열</b></div><div class="home-actions">${button("작전 개시", "stage", "primary large", "arrow")}${button("실전 배치", "campaign-deploy", "ghost", "deck")}</div><p class="build-tag">PLAYABLE ALPHA <span>v0.1 / LOCAL SAVE</span></p></div>
 <aside class="command-panel"><div class="panel-head"><span>COMMAND CENTER</span><span class="live-dot"></span></div><div class="command-status"><small>현재 위협 단계</small><strong>LEVEL <em>01</em></strong><div class="threat-bar"><i></i><i></i><i></i><i></i><i></i></div><p>연구시설에서 균열 반응이 감지되었습니다.</p></div><button class="mission-tile" data-action="stage"><div class="mission-map">${icon("shield")}<span>LAB 01</span></div><small>STORY OPERATION</small><h3>청록 연구시설 ${icon("chevron")}</h3><p>4 STAGES <span>·</span> 5 OPERATORS</p></button><div class="operation-progress"><span>최고 기록</span><b>${String(s.bestWave).padStart(2, "0")} <small>WAVE</small></b></div><div class="mini-progress"><i style="width:${Math.min(100, s.bestWave)}%"></i></div><div class="dispatch-note">${icon("info")}<span>육성은 강함을, 전략은 승률을.<br>그리고 운은 한 판을 뒤집습니다.</span></div></aside>
 </section>`;
}
export function heroScreen(s: SaveData, id: string) {
  const h = heroById[id],
    p = s.heroes[id];
  return `<section class="collection-screen"><div class="section-heading"><div><span class="eyebrow">OPERATOR ARCHIVE</span><h1>요원 기록 <small>${heroes.length} / ${heroes.length}</small></h1></div><span class="muted">당신의 가능성을 함께할 요원들</span></div><div class="collection-layout"><div class="hero-grid">${[...heroes].sort(dealerFirst).map((v) => heroCard(v, s, v.id === id)).join("")}</div><aside class="hero-detail" style="--hero-color:${h.color}"><div class="detail-portrait">${portrait(id)}<span>${h.code}</span></div><div class="detail-body"><small class="eyebrow">${gradeNames[h.grade]} / ${heroElementName(h)} / ${h.role}</small><h2>${h.name} <span>Lv.${p.level}</span></h2><p>${h.description}</p><div class="hero-meta-line"><span>${gradeNames[h.grade]}</span><span>${heroElementName(h)} 속성</span></div><div class="stats-grid"><div><small>ATK</small><b>${Math.round(h.atk * (1 + 0.04 * (p.level - 1)))}</b></div><div><small>HP</small><b>${Math.round(h.hp * (1 + 0.04 * (p.level - 1)))}</b></div><div><small>ASPD</small><b>${h.speed}/s</b></div></div><div class="skill-line">${icon("bolt")}<span>${h.skill}</span></div>${button(p.level >= 50 ? "최대 레벨" : `레벨업 · ${num(p.level * 60)} C`, "hero-upgrade", "primary", "science", `data-id="${id}" ${p.level >= 50 || s.credits < p.level * 60 ? "disabled" : ""}`)}<div class="future-growth"><span>돌파 0</span><span>스킬 Lv.1</span><span>장비 —</span><span>호감도 0</span></div><small class="muted">돌파·스킬·장비·호감도는 후속 버전에서 개방</small><details><summary>전투 합성 성장표</summary>${h.evolution.map((e, i) => `<p>${"★".repeat(i + 1)} ${e.text}</p>`).join("")}</details></div></aside></div></section>`;
}
export function deckScreen(s: SaveData) {
  return `<section class="deck-screen"><div class="section-heading"><div><span class="eyebrow">SQUAD FORMATION</span><h1>출격 덱 편성 <small>${s.deck.length} / 10</small></h1></div>${button("출격 준비", "stage", "primary", "arrow")}</div><div class="deck-info">${icon("info")}<p>전투에서는 영웅을 직접 선택해 정가로 구매합니다. <strong>영웅마다 가격이 다르며 같은 영웅을 반복 구매하면 가격이 오릅니다. 구매 목록은 딜러 우선, 서포터 하단 순서입니다.</strong><br>속성 연계: 물+전기=전도 · 불+전기=과부하 · 물+불=증발 · 어둠+불=흑염 · 어둠+물=침식 · 어둠+전기=공허 감전</p><span>자동 저장 ${icon("check")}</span></div><div class="deck-grid">${[...heroes].sort(dealerFirst).map((h) => heroCard(h, s, s.deck.includes(h.id), "toggle-deck")).join("")}</div><div class="deck-footer"><span>최소 1명 · 최대 10명 / 같은 별 2명 → 다음 단계 1명</span><div>${button("B급 10명", "deck-all", "ghost")}${button("A급 5인", "deck-recommended", "ghost")}${button("S급 4인", "deck-s", "ghost")}${button("SR 2인", "deck-sr", "ghost")}</div></div></section>`;
}
export function stageScreen(s: SaveData) {
 return `<section class="stage-screen"><div class="section-heading"><div><span class="eyebrow">OPERATION SELECT</span><h1>연구시설 방어</h1></div></div><p>소환 등급을 선택한 뒤 빈 배치 칸을 누르면 해당 등급 요원이 소환됩니다. 배치한 요원은 이동하거나 10초 안에 배치를 되돌릴 수 있습니다.</p><div class="remake-map-grid">${battleMaps.map((m,i)=>`<article class="remake-map-card"><span class="eyebrow">SECTOR 0${i+1}</span><svg viewBox="0 0 800 800" role="img" aria-label="${m.name} 이동 경로"><rect width="800" height="800" fill="#122330"/>${m.slots.map(s=>`<rect x="${s.x-17}" y="${s.y-17}" width="34" height="34" fill="#315349"/>`).join('')}<polyline points="${m.path.map(p=>`${p.x},${p.y}`).join(' ')}" fill="none" stroke="#99dbed" stroke-width="25"/>${m.obstacles.map(o=>`<rect x="${o.x-22}" y="${o.y-22}" width="44" height="44" fill="#ba9462"/>`).join('')}</svg><h2>${m.name}</h2><p>${m.description}</p><small>배치 가능 ${m.slots.length}칸 · 무한 웨이브 · 요원 최대 22명</small>${button('이 지역에서 시작','start-battle','primary','battle',`data-id="${m.id}"`)}</article>`).join('')}</div></section>`;
}
export function resultScreen(r: BattleResult) {
  return `<section class="result-screen ${r.won ? "won" : "lost"}"><span class="eyebrow">OPERATION REPORT / LAB 01</span><h1>RUN OVER</h1><p>방어선이 무너졌습니다. 기록을 갱신하고 더 높은 웨이브에 도전하세요.</p><div class="result-layout"><div class="mvp-card">${r.mvp ? portrait(r.mvp) : icon("shield")}<span>MOST VALUABLE OPERATOR</span><h2>${r.mvp ? heroById[r.mvp].name : "출격 대기"}</h2></div><div class="result-stats"><div><small>작전 시간 (게임 시간)</small><b>${time(r.time)}</b></div><div><small>도달 웨이브</small><b>${r.wave}</b></div><div><small>처치 수</small><b>${num(r.kills)}</b></div><div><small>최고 합성</small><b class="stars">${"★".repeat(r.highestStar)}</b></div><div><small>전투 획득 GOLD</small><b>${num(r.gold)}</b></div><div><small>영구 보상 CREDIT</small><b class="mint">+${num(r.credits)}</b></div><div class="result-builds"><small>BUILD RECORD</small><p>${
    Object.entries(r.builds)
      .filter(([, n]) => n)
      .map(
        ([key, n]) =>
          `<span>${buildNames[key as keyof typeof buildNames]} ${n}</span>`,
      )
      .join("") || "기본 전술"
  }</p></div><div class="result-builds"><small>ELEMENT REACTIONS</small><p>${
    Object.entries(r.reactions)
      .filter(([, n]) => n)
      .sort((a, b) => b[1] - a[1])
      .slice(0, 4)
      .map(([key, n]) => `<span>${({ conduct: "전도", overload: "과부하", vaporize: "증발", blackflame: "흑염", corrosion: "침식", voidshock: "공허 감전" } as Record<string, string>)[key] ?? key} ${n}</span>`)
      .join("") || "반응 없음"
  }</p></div></div></div><div class="dps-panel open"><b>요원 전투 기록 · 종료 시점 최근 10초 DPS</b>${(r.ranking??[]).map(u=>`<div class="dps-row"><span>${heroById[u.heroId].name} ${"★".repeat(u.star)}</span><b>${u.dps.toFixed(1)}</b><span>${u.kills}킬</span><span>${num(u.damage)}</span></div>`).join("")}</div><section class="strategy-results"><h3>전략 기록</h3><p>사용 ${r.strategy?.spent??0}G · 잔액 ${r.strategy?.remaining??0}G</p><p>투자: ${r.strategy?.investments.slice(0,5).map(v=>heroById[v.heroId].name+" "+v.gold+"G").join(" · ")||"없음"}</p><p>상위 조합: ${Object.entries(r.strategy?.triples??{}).map(([k,v])=>k+" "+v+"회").join(" · ")||"없음"}</p><p>편성 링크: ${Object.entries(r.strategy?.links??{}).map(([k,v])=>k+" "+v+"회").join(" · ")||"없음"}</p><p>처치 순위: ${r.ranking?.slice().sort((a,b)=>b.kills-a.kills).slice(0,5).map(v=>heroById[v.heroId].name+" "+v.kills).join(" · ")}</p><p>지원·제어: ${r.strategy?.support.slice(0,5).map(v=>heroById[v.heroId].name+" 저지 "+v.block.toFixed(1)+"초 / 감속 "+v.slow.toFixed(1)+"초 / 간접 피해(추정) "+Math.round(v.damage)).join(" · ")}</p></section><div class="result-actions">${button("홈으로", "home", "ghost", "home")}${button("다시 도전", "start-battle", "primary", "arrow")}</div><small class="muted">영구 보상이 저장되었습니다. 전투 합성·특성·유물은 초기화됩니다.</small></section>`;
}
export function settingsScreen(s: SaveData, available: boolean) {
  return `<section class="settings-screen"><div class="section-heading"><div><span class="eyebrow">SYSTEM CONFIGURATION</span><h1>설정</h1></div></div><div class="settings-grid"><div class="settings-panel"><h3>게임 환경</h3>${(["sound", "shake", "lowEffects"] as const).map((key, i) => `<button class="setting-row" data-action="setting" data-id="${key}" aria-pressed="${s.settings[key]}"><span><b>${["효과음", "보스 화면 흔들림", "저사양 효과"][i]}</b><small>${["공격 · 소환 · 합성 · 보스 효과음", "기본 OFF · 짧은 보스 등장 효과", "이펙트 표시를 최대 18개로 제한 · 자동 성능 조절과 병행"][i]}</small></span><i class="toggle ${s.settings[key] ? "on" : ""}"></i></button>`).join("")}<h3>튜토리얼</h3><p class="muted">첫 소환부터 특성 선택까지, 여섯 단계의 작전 안내.</p>${button("다음 전투에서 튜토리얼 다시 보기", "tutorial-reset", "ghost", "info")}</div><div class="settings-panel"><h3>저장 데이터 <span class="status-label">${available ? "LOCAL SAVE" : "저장 불가 · 백업 필요"}</span></h3><p class="muted">이 브라우저에 자동 저장됩니다. 다른 기기로 이동할 때 저장 파일을 내보낸 뒤 가져오세요. 서버 동기화는 지원하지 않습니다.</p><div class="save-facts"><span>저장 버전 <b>1</b></span><span>출격 횟수 <b>${s.runs}</b></span><span>최고 기록 <b>${s.bestWave} WAVE</b></span></div>${button("저장 파일 내보내기", "export", "ghost", "download")}${button("저장 파일 가져오기", "import", "ghost", "deck")}<input type="file" id="save-file" accept="application/json,.json" hidden/><h3>조작 방법</h3><p class="muted">클릭 / 터치: 요원 선택<br>드래그 또는 요원 → 빈 슬롯 클릭: 이동<br>SPACE: 세라 구매 선택 · M: 가능한 합성 · 더블클릭: 자동 합성<br>ESC: 일시정지 · 1 / 2: 게임 속도<br>영웅 카드 선택 → 빈칸: 구매</p></div></div></section>`;
}

