import {describe,it,expect} from 'vitest';
import {defaultSave,localTestResetSave,parseSave} from '../src/systems/SaveSystem';
import {armorCatalog,campaignEquipmentDropChance,campaignEquipmentRarity,equipItem,equipmentBonus,equipmentCraftCost,equipmentSalvageValue,equipmentShopPrice,heroWeaponGroup,makeEquipment,necklaceCatalog,rarityMax,weaponCatalog} from '../src/data/equipment';
import {heroes} from '../src/data/heroes';
import {BattleModel} from '../src/systems/BattleModel';
import {attack,castAutoSkill,stepActions} from '../src/systems/ActionCombat';

const emptyEquipmentSave=()=>{const s=defaultSave();s.equipmentInventory=[];for(const h of Object.values(s.heroes))h.equipment=[];return s;};
const equip= (s:ReturnType<typeof defaultSave>,heroId:string,templateId:string,rarity:'B'|'A'|'S'|'SR'='SR')=>{const item=makeEquipment(templateId,rarity,s.equipmentInventory.length+1,`${heroId}-${templateId}`);s.equipmentInventory.push(item);expect(equipItem(s,heroId,item.id)).toBe(true);return item;};

describe('permanent stars and equipment',()=>{
 it('clears every item and equipped reference for a local test reset and keeps it empty after parsing',()=>{const reset=localTestResetSave();expect(reset.equipmentInventory).toEqual([]);expect(reset.equipmentMaterials).toBe(0);expect(Object.values(reset.heroes).every(h=>h.equipment.length===0)).toBe(true);const loaded=parseSave(JSON.stringify(reset));expect(loaded.equipmentInventory).toEqual([]);expect(Object.values(loaded.heroes).every(h=>h.equipment.length===0)).toBe(true);});
 it('owns every operator and every equipment template in the test build',()=>{const s=defaultSave(),catalog=[...weaponCatalog,...armorCatalog,...necklaceCatalog];expect(heroes.every(h=>s.heroes[h.id].owned)).toBe(true);for(const template of catalog)expect(s.equipmentInventory.some(v=>v.templateId===template.id),template.id).toBe(true);expect(s.equipmentInventory.length).toBeLessThanOrEqual(100);});
 it('assigns all 21 heroes a supported weapon group and gives every starter a compatible B weapon',()=>{const s=defaultSave();expect(Object.keys(heroWeaponGroup)).toHaveLength(heroes.length);for(const h of heroes)expect(heroWeaponGroup[h.id]).toBeTruthy();for(const id of s.deck){const item=s.equipmentInventory.find(v=>v.equippedBy===id);expect(item?.rarity).toBe('B');expect(item?.weaponGroup).toBe(heroWeaponGroup[id]);}});
 it('keeps duplicate item templates as independent instances and rejects incompatible weapons',()=>{const s=defaultSave(),template=weaponCatalog.find(v=>v.weaponGroup==='sniper')!;const a=makeEquipment(template.id,'A',100,'a'),b=makeEquipment(template.id,'A',101,'b');s.equipmentInventory.push(a,b);expect(a.id).not.toBe(b.id);expect(equipItem(s,'arin',a.id)).toBe(true);expect(equipItem(s,'sera',b.id)).toBe(false);});
 it('applies enhancement and permanent stars without legacy hero levels',()=>{const s=defaultSave(),u=s.heroes.sera,item=s.equipmentInventory.find(v=>v.equippedBy==='sera')!;item.enhance=rarityMax.B;u.stars=3;u.level=50;const m=new BattleModel(s),unit=m.addUnit('sera');const boosted=m.stats(unit).atk;u.level=1;expect(m.stats(unit).atk).toBe(boosted);expect(equipmentBonus(s,'sera').attack).toBeCloseTo(item.attack*1.25);});
 it('migrates old saves and repairs missing equipment safely',()=>{const old=defaultSave() as any;delete old.equipmentInventory;delete old.equipmentMaterials;for(const p of Object.values(old.heroes) as any[])delete p.stars;const s=parseSave(JSON.stringify(old));expect(s.heroes.sera.stars).toBe(1);expect(s.equipmentInventory.some(v=>v.equippedBy==='sera'&&v.slot==='weapon')).toBe(true);expect(s.equipmentMaterials).toBe(30);});
 it('migrates shop gold and prices every equipment rarity in ascending order',()=>{const old=defaultSave() as any;delete old.equipmentGold;expect(parseSave(JSON.stringify(old)).equipmentGold).toBe(0);const saved=defaultSave();saved.equipmentGold=345;expect(parseSave(JSON.stringify(saved)).equipmentGold).toBe(345);expect([equipmentShopPrice.B,equipmentShopPrice.A,equipmentShopPrice.S,equipmentShopPrice.SR]).toEqual([40,120,360,1000]);});
 it('caps every rarity at +5 and clamps legacy over-enhanced gear',()=>{expect(rarityMax).toEqual({B:5,A:5,S:5,SR:5});const old=defaultSave();old.equipmentInventory[0].enhance=20;expect(parseSave(JSON.stringify(old)).equipmentInventory.find(v=>v.id===old.equipmentInventory[0].id)?.enhance).toBe(5);});
 it('makes higher-rarity crafting progressively expensive and returns more material for enhanced gear',()=>{expect(equipmentCraftCost.B.material).toBeLessThan(equipmentCraftCost.A.material);expect(equipmentCraftCost.A.gold).toBeLessThan(equipmentCraftCost.S.gold);const item=makeEquipment(armorCatalog[0].id,'A');const base=equipmentSalvageValue(item);item.enhance=3;expect(equipmentSalvageValue(item)).toBe(base+9);});
 it('raises the guaranteed equipment floor through later maps',()=>{expect(campaignEquipmentRarity(0,false,.99,0)).toBe('B');expect(campaignEquipmentRarity(2,false,.99,0)).toBe('A');expect(campaignEquipmentRarity(5,false,.99,0)).toBe('S');expect(campaignEquipmentRarity(7,true,.99,0)).toBe('SR');});
 it('keeps equipment drops occasional and rewards boss operations more often',()=>{expect(campaignEquipmentDropChance(false)).toBe(.22);expect(campaignEquipmentDropChance(true)).toBe(.45);expect(campaignEquipmentDropChance(false)).toBeLessThan(campaignEquipmentDropChance(true));});
 it('awards permanent equipment-shop loot value for monster kills',()=>{const m=new BattleModel(defaultSave()),u=m.addUnit('sera');m.spawn('armored');const e=m.enemies.find(v=>v.active)!;m.damage(e,e.hp+1,u);expect(m.equipmentGoldEarned).toBeGreaterThan(0);m.finish(true);expect(m.result?.equipmentGold).toBe(m.equipmentGoldEarned);});
 it('applies every armor identity in combat instead of description only',()=>{
  const field=makeEquipment('armor-field','SR'),barrier=makeEquipment('armor-barrier','SR'),ranged=makeEquipment('armor-ranged','SR'),guardian=makeEquipment('armor-guardian','SR');
  expect(field.hp).toBeGreaterThan(barrier.hp);expect(guardian.hp).toBeGreaterThan(ranged.hp);
  const run=(template:string,source:'melee'|'ranged'='melee',blocking=0,guard=0)=>{const s=emptyEquipmentSave();equip(s,'yuria',template);const m=new BattleModel(s),u=m.addUnit('yuria');u.blockingCount=blocking;u.guardHp=guard;const hp=u.hp;m.hurtUnit(u,100,source);return {lost:hp-u.hp,guard:u.guardHp??0};};
  expect(run('armor-ranged','ranged').lost).toBeCloseTo(82);
  expect(run('armor-guardian','melee',1).lost).toBeCloseTo(85);
  expect(run('armor-barrier','melee',0,80).lost).toBeCloseTo(0);
  expect(run('armor-field','melee',0,80).lost).toBeCloseTo(20);
 });
 it('makes special weapons strengthen real skill damage, healing and shields',()=>{
  const damage=(special:boolean)=>{const s=emptyEquipmentSave();if(special)equip(s,'reina','rifle-3');const m=new BattleModel(s,()=>.9),u=m.addUnit('reina');m.start();m.wave.queue=[];m.spawn('brute');const e=m.enemies.find(v=>v.active)!;e.x=u.x+10;e.y=u.y;e.hp=e.maxHp=100000;u.skillCharge=100;castAutoSkill(m,u,e);for(let i=0;i<90;i++)stepActions(m,1/60);return 100000-e.hp;};
  const support=(special:boolean)=>{const s=emptyEquipmentSave();if(special)equip(s,'rhea','catalyst-3');const m=new BattleModel(s),u=m.addUnit('rhea'),ally=m.addUnit('reina');m.start();m.wave.queue=[];ally.hp=ally.maxHp*.5;u.skillCharge=100;castAutoSkill(m,u);return {heal:ally.hp-ally.maxHp*.5,guard:ally.guardHp??0};};
  const shield=(special:boolean)=>{const s=emptyEquipmentSave();if(special)equip(s,'yuria','guardian-3');const m=new BattleModel(s),u=m.addUnit('yuria');m.start();m.wave.queue=[];u.skillCharge=100;castAutoSkill(m,u);return u.guardHp??0;};
  expect(damage(true)).toBeGreaterThan(damage(false)*1.1);expect(support(true).heal).toBeGreaterThan(support(false).heal*1.1);expect(support(true).guard).toBeGreaterThan(support(false).guard*1.1);expect(shield(true)).toBeGreaterThan(shield(false)*1.1);
 });
 it('keeps necklaces off global and skill attack while adding basic elemental damage',()=>{
  const run=(necklace:boolean,skill:boolean)=>{const s=emptyEquipmentSave();if(necklace)equip(s,'reina','necklace-water');const m=new BattleModel(s,()=>.9),u=m.addUnit('reina');m.start();m.wave.queue=[];m.spawn('brute');const e=m.enemies.find(v=>v.active)!;e.x=u.x+10;e.y=u.y;e.hp=e.maxHp=100000;const atk=m.stats(u).atk;if(skill){u.skillCharge=100;castAutoSkill(m,u,e);}else attack(m,u,e);for(let i=0;i<90;i++)stepActions(m,1/60);return {atk,damage:100000-e.hp,water:e.waterMark};};
  const plain=run(false,false),neck=run(true,false),plainSkill=run(false,true),neckSkill=run(true,true);expect(neck.atk).toBe(plain.atk);expect(neck.damage).toBeGreaterThan(plain.damage);expect(neck.water).toBeGreaterThan(0);expect(neckSkill.damage).toBeCloseTo(plainSkill.damage);
 });
});
