import type {SaveData} from '../data/types';
import {heroById} from '../data/heroes';
import {raidBosses,weeklyRaidBosses,refreshRaid,raidRank,RAID_DURATION} from '../data/raid';
import {button,combatPortrait,num} from './components';
import {assetUrl} from '../utils/assets';
import {raidEquipmentCatalog} from '../data/equipment';
import {formationRole} from '../data/combatRoles';

export type RaidRuntime={bossIndex:number;time:number;damage:number;lastHit?:number;bossHp:number;bossMaxHp:number;phase:number;pattern:string;manualCooldown:number;squadHp:number[];summons:number;running:boolean};

export function raidScreen(s:SaveData,selected=0,runtime?:RaidRuntime){
 const r=refreshRaid(s),bosses=weeklyRaidBosses(),boss=bosses[selected]??bosses[0],squad=s.campaign?.squad.slice(0,5)??[];
 if(runtime){
  const hp=Math.max(0,runtime.bossHp/runtime.bossMaxHp*100),vfxRow=runtime.pattern.includes(`광역`)?0:runtime.pattern.includes(`전방`)?1:runtime.pattern.includes(`후열`)?2:runtime.pattern.includes(`소환`)?3:-1,frame=1+(Math.floor(RAID_DURATION-runtime.time)%6);
  const bossAttacking=vfxRow>=0,bossPose=bossAttacking?'attack':'idle',galeState=runtime.pattern==='DEATH'?'death':runtime.pattern.startsWith('PHASE')?'phase':runtime.pattern.includes('광역')?'pattern':runtime.pattern.includes('수동')?'hit':runtime.time===RAID_DURATION?'prepare':bossPose;
  const bossArt=assetUrl(boss.id==='gale-colossus'?`/assets/generated/raid-v3/bosses/gale-colossus/${galeState}.webp`:`/assets/generated/raid-v2/bosses/${boss.id}/${bossPose}-sheet.webp`);
  const fighters=squad.map((id,i)=>{const role=formationRole(id),melee=heroById[id].rangeType==='melee';return `<div class="raid-fighter ${runtime.squadHp[i]<=0?'down':''} ${role} ${melee?'melee':'ranged'}" style="--fighter:${i}"><span class="raid-hero-sprite" style="--sprite:url('${assetUrl(`/assets/generated/raid-v2/heroes/${id}-skill.webp`)}')" role="img" aria-label="${heroById[id].name} 전투 모습"></span>${role==='support'?'':`<span class="raid-hero-projectile basic" style="--projectile:url('${assetUrl(`/assets/generated/raid-v3/heroes/${id}/basic.webp`)}')"></span>`}<span class="raid-hero-projectile skill" style="--projectile:url('${assetUrl(`/assets/generated/raid-v3/heroes/${id}/skill.webp`)}')"></span><span class="raid-hero-impact" style="--impact:url('${assetUrl(`/assets/generated/raid-v3/heroes/${id}/impact.webp`)}')"></span><b>${heroById[id].name}</b></div>`;}).join('');
  const bossProjectile=boss.id==='gale-colossus'?`<span class="raid-boss-projectile" style="--boss-projectile:url('${assetUrl('/assets/generated/raid-v3/bosses/gale-colossus/projectile-lifecycle.webp')}')"></span>`:'';
  const summons=Array.from({length:runtime.summons},(_,i)=>`<img class="raid-summon" style="--summon:${i}" src="${assetUrl(`/assets/generated/raid-v2/summons/${boss.id}.webp`)}" alt="보스 소환체">`).join('');
  return `<section class="raid-screen raid-live"><header><span>WEEKLY BOSS RAID</span><h1>${boss.name}</h1><b>${Math.ceil(runtime.time)}초</b></header><div class="raid-boss-stage phase-${runtime.phase} pattern-${Math.max(0,vfxRow)}" style="--raid-color:${boss.color}"><div class="raid-arena"><div class="raid-field-squad">${fighters}</div><div class="raid-boss-silhouette"><span class="raid-boss-main ${bossPose} ${boss.id==='gale-colossus'?'v3':''}" style="--boss-sheet:url('${bossArt}')" role="img" aria-label="${boss.name}"></span>${runtime.lastHit?`<b class="raid-damage-pop">-${num(Math.round(runtime.lastHit))}</b>`:''}</div>${bossProjectile}${summons}<img class="raid-impact-core" src="${assetUrl('/assets/generated/raid-v2/vfx/impact-burst.webp')}" alt=""></div>${vfxRow>=0?`<div class="raid-pattern-warning"><img src="${assetUrl(`/assets/generated/raid-v2/vfx/${vfxRow===3?'summon-portal':'danger-telegraph'}.webp`)}" alt=""><b>${['광역 폭풍','전방 파괴','후열 저격','균열 소환'][vfxRow]}</b><i></i></div>`:``}<div class="raid-boss-hp"><span><b>PHASE ${runtime.phase}</b><em>${num(Math.max(0,Math.ceil(runtime.bossHp)))} / ${num(runtime.bossMaxHp)}</em></span><i style="width:${hp}%"></i></div><strong>${runtime.pattern}</strong><small>소환체 ${runtime.summons} · 누적 피해 ${num(Math.floor(runtime.damage))}</small></div><div class="raid-live-squad">${squad.map((id,i)=>`<div>${combatPortrait(id)}<b>${heroById[id].name}</b><i><span style="width:${runtime.squadHp[i]??100}%"></span></i><small>HP ${Math.max(0,Math.round(runtime.squadHp[i]??100))}%</small></div>`).join('')}</div><div class="raid-live-actions">${button(s.campaign?.autoSkills?'AUTO 스킬 ON':'AUTO 스킬 OFF','raid-auto',s.campaign?.autoSkills?'primary':'ghost')}${button(runtime.manualCooldown>0?`수동 스킬 ${runtime.manualCooldown}초`:'수동 집중 스킬','raid-manual','primary','',runtime.manualCooldown>0?'disabled':'')}${button('레이드 포기','raid-retreat','ghost')}</div></section>`;
 }
 const settlement=r.lastSettlement?`<small class="raid-settlement">지난 주 ${r.lastSettlement}</small>`:'';
 return `<section class="raid-screen"><header><span class="eyebrow">WEEKLY ROTATION · ${r.week}</span><h1>보스 레이드</h1><p>5명 편성 · 제한 시간 ${RAID_DURATION}초 · 누적 피해로 순위와 보상을 결정합니다.</p>${settlement}</header><div class="raid-summary"><span><small>오늘 남은 도전</small><b>${r.attempts} / 3</b></span><span><small>일일 최고 피해</small><b>${num(r.dailyBest)}</b></span><span><small>주간 누적 피해</small><b>${num(r.weeklyDamage)}</b></span><span><small>주간 등급</small><b>${raidRank(r.weeklyBest)}</b></span></div><div class="raid-boss-list">${bosses.map((v,i)=>`<button data-action="raid-boss" data-id="${i}" class="${i===selected?'selected':''}" style="--raid-color:${v.color}"><img class="raid-boss-card-art" src="${assetUrl(v.image)}" alt=""><small>ROTATION ${i+1}</small><b>${v.name}</b><span>${v.title}</span><em>${v.pattern}</em></button>`).join('')}</div><section class="raid-brief"><h2>${boss.name}</h2><p>체력 70%와 40%에서 페이즈가 전환됩니다. 광역기·전방 파괴·후열 저격·소환 패턴이 순환합니다.</p><div class="raid-squad">${squad.map(id=>`<span>${combatPortrait(id)}<b>${heroById[id].name}</b></span>`).join('')}${Array.from({length:Math.max(0,5-squad.length)},()=>'<span class="empty"><b>빈 슬롯</b></span>').join('')}</div><p>캠페인 편성, 별 성장, 장비, 스킬 레벨이 그대로 적용됩니다.</p><div>${button('편성 변경','deck','ghost')}${button(r.attempts>0&&squad.length===5?'레이드 시작':r.attempts<=0?'오늘 도전 완료':'5명 편성 필요','raid-start','primary','',r.attempts>0&&squad.length===5?'':'disabled')}</div></section><div class="raid-rewards"><b>누적 피해 보상</b><span>25만 · 300C</span><span>75만 · 재료 15</span><span>150만 · 1,000G</span><span>주간 등급 보상은 다음 주 첫 접속 시 정산</span></div><div class="raid-rewards raid-gear"><b>보스 전용 장비</b>${raidEquipmentCatalog.map(v=>`<span><strong>${v.name}</strong><small>${v.effect}</small></span>`).join('')}<em>보스 체력 35% 이상 피해 시 30% 확률 · 처치 시 확정</em></div></section>`;
}
