import type {RecruitResult} from '../systems/RecruitSystem';
import {combatPortrait,portrait,esc} from './components';
import {assetUrl} from '../utils/assets';
import {RecruitSpritePlayer,preloadRecruitSprites} from './RecruitSpritePlayer';

/** Presentation only: rewards are committed before this controller is created. */
export function mountRecruitReveal(host:HTMLElement,results:RecruitResult[],sound:(tier:string)=>void,stopSound:()=>void,onClose:()=>void){
 const tier=(v:RecruitResult)=>v.grade==='SR'?'ssr':v.grade==='S'?'sr':'normal';
 const label=(v:RecruitResult)=>v.grade==='S'?'SR':v.displayGrade;
 const previousFocus=document.activeElement as HTMLElement|null;
 const bodyStyle=document.body.getAttribute('style'),htmlStyle=document.documentElement.getAttribute('style');
 const x=scrollX,y=scrollY;
 document.body.style.position='fixed';document.body.style.top=`-${y}px`;document.body.style.left=`-${x}px`;document.body.style.width='100%';document.body.style.overflow='hidden';document.documentElement.style.overflow='hidden';
 host.innerHTML=`<section style="--recruit-bg:url(${assetUrl('/assets/ui/recruit/backdrop.png')})" class="recruit-reveal recruit-sprite-mode" role="dialog" aria-modal="true" aria-label="모집 결과"><header><small>RIFT RESONANCE</small><h2>균열 공명 · ${results.length}명</h2><p aria-live="polite">카드를 정렬하고 있습니다</p></header><div class="reveal-grid count-${results.length}">${results.map((v,i)=>`<button class="reveal-card" data-card="${i}" disabled style="--arrival:${i*70}ms" aria-label="${i+1}번째 카드 공개"><span class="reveal-card-inner"><span class="reveal-back"><img class="recruit-card-sprite" hidden alt="" aria-hidden="true"></span><span class="reveal-front">${combatPortrait(v.hero.id)}<strong>${esc(v.hero.name)}</strong><small>${label(v)} · ${v.newHero?'NEW':`조각 +${v.fragments}`}</small></span></span></button>`).join('')}</div><footer><button data-reveal="all">전체 공개</button><button data-reveal="skip">연출 건너뛰기</button><button data-reveal="close">확인 · 닫기</button></footer><div class="reveal-focus" hidden></div></section>`;
 const root=host.querySelector<HTMLElement>('.recruit-reveal')!,cards=Array.from(root.querySelectorAll<HTMLButtonElement>('[data-card]')),focus=root.querySelector<HTMLElement>('.reveal-focus')!,status=root.querySelector('p')!;
 const player=new RecruitSpritePlayer(),sprites=cards.map(c=>c.querySelector<HTMLImageElement>('.recruit-card-sprite')!);
 const timers=new Set<ReturnType<typeof setTimeout>>();let disposed=false,skipped=false,ready=false,busy=false,queue:number[]=[];
 const later=(fn:()=>void,ms:number)=>{const t=setTimeout(()=>{timers.delete(t);if(!disposed)fn();},ms);timers.add(t);};
 const clear=()=>{skipped=true;player.clear();timers.forEach(clearTimeout);timers.clear();stopSound();};
 const mark=(i:number)=>{player.stop(sprites[i]);cards[i].classList.remove('turning');cards[i].classList.add('revealed');cards[i].setAttribute('aria-label',`${results[i].hero.name} ${label(results[i])} 공개됨`);cards[i].disabled=true;};
 const finish=()=>{const fx=focus.querySelector<HTMLImageElement>('.reveal-fx-image');if(fx)player.stop(fx);focus.hidden=true;focus.innerHTML='';busy=false;cards.forEach((c)=>{c.disabled=c.classList.contains('revealed');});status.textContent=cards.every(c=>c.classList.contains('revealed'))?'모든 요원을 확인했습니다':'카드를 눌러 요원을 확인하세요';if(queue.length)reveal(queue.shift()!);};
 const reveal=(i:number)=>{if(!ready||busy||cards[i].classList.contains('revealed'))return;busy=true;cards.forEach(c=>c.disabled=true);const v=results[i],t=tier(v);cards[i].classList.add('turning');sound(t);player.play(sprites[i],'turn',400,false,()=>{if(disposed)return;cards[i].classList.remove('turning');mark(i);if(t==='normal'){finish();return;}focus.className=`reveal-focus focus-${t}`;focus.innerHTML=`<div class="reveal-effects" aria-hidden="true"><img class="reveal-fx-image" alt=""></div><div class="reveal-hero">${portrait(v.hero.id)}<div><small>${label(v)}</small><h2>${esc(v.hero.name)}</h2><p>${v.newHero?'새로운 요원 합류':`중복 요원 · 승급 조각 +${v.fragments}`}</p></div></div>`;focus.hidden=false;status.textContent=`${label(v)} ${v.hero.name} 공개 중`;player.play(focus.querySelector<HTMLImageElement>('.reveal-fx-image')!,t==='ssr'?'ssr-reveal':'sr-reveal',3000);later(()=>{stopSound();finish();},3000);});};
 const settle=()=>{ready=true;root.classList.add('settled');cards.forEach((c,i)=>{const t=tier(results[i]);c.classList.add(`reveal-${t}`);c.disabled=c.classList.contains('revealed');if(!c.disabled&&!skipped){if(t==='sr')player.play(sprites[i],'sr-charge',1600,true);if(t==='ssr')player.play(sprites[i],'sr-charge',700,false,()=>{if(!disposed&&!c.classList.contains('revealed'))player.play(sprites[i],'ssr-crack',1200);});}});status.textContent='카드를 눌러 요원을 확인하세요';};
 void preloadRecruitSprites().then(()=>{if(disposed||skipped)return;cards.forEach((_,i)=>later(()=>{sprites[i].hidden=false;player.play(sprites[i],'arrival',560);},i*70));later(settle,(results.length-1)*70+560);}).catch(()=>{if(!disposed&&!skipped)status.textContent='이미지를 불러오지 못했습니다. 건너뛰기로 결과를 확인할 수 있습니다.';});
 const click=(e:Event)=>{const b=(e.target as HTMLElement).closest<HTMLButtonElement>('button');if(!b)return;if(b.dataset.card!==undefined){reveal(Number(b.dataset.card));return;}switch(b.dataset.reveal){case 'close':onClose();break;case 'skip':clear();queue=[];busy=false;settle();results.forEach((_,i)=>mark(i));finish();break;case 'all':if(busy||!ready)return;queue=results.map((_,i)=>i).filter(i=>!cards[i].classList.contains('revealed'));if(queue.length)reveal(queue.shift()!);break;}};
 const keys=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();onClose();}if(e.key==='Tab'){const buttons=Array.from(root.querySelectorAll<HTMLButtonElement>('button:not(:disabled)')).filter(b=>!b.closest('[hidden]'));const first=buttons[0],last=buttons.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};
 root.addEventListener('click',click);root.addEventListener('keydown',keys);root.querySelector<HTMLButtonElement>('[data-reveal="skip"]')?.focus({preventScroll:true});
 return ()=>{if(disposed)return;disposed=true;clear();root.removeEventListener('click',click);root.removeEventListener('keydown',keys);host.innerHTML='';if(bodyStyle===null)document.body.removeAttribute('style');else document.body.setAttribute('style',bodyStyle);if(htmlStyle===null)document.documentElement.removeAttribute('style');else document.documentElement.setAttribute('style',htmlStyle);scrollTo(x,y);if(previousFocus?.isConnected)previousFocus.focus({preventScroll:true});};
}
