import { heroes, heroById, buildNames } from "../data/heroes";
import type { SaveData } from "../data/types";
import type { BattleResult } from "../systems/BattleModel";
import { button, heroCard, icon, num, portrait, time } from "./components";
export function home(s: SaveData) {
  return `<section class="home-screen">
 <div class="city-scene" aria-hidden="true"><div class="city-grid"></div><div class="rift-ring"></div><div class="city-buildings">${Array.from({ length: 18 }, (_, i) => `<i style="--h:${22 + ((i * 29) % 61)}%;--w:${25 + ((i * 17) % 35)}px"></i>`).join("")}</div><div class="ground-grid"></div></div>
 <div class="hero-art"><span class="orbit one"></span><span class="orbit two"></span>${portrait("sera", "featured")}<div class="character-caption"><span>OPERATOR / 05</span><b>세라 <small>SERA</small></b><p>“지휘관, 사선은 제가 확보할게요.”</p></div></div>
 <div class="home-copy"><span class="eyebrow"><i class="live-dot"></i> RIFT RESPONSE DIVISION</span><h1>BEYOND<br>THE <em>RIFT.</em></h1><p class="home-subtitle">균열 너머의 위협.<br>당신만의 작전으로 돌파하세요.</p><div class="chapter-label"><span>CHAPTER 01</span><b>무너진 도시의 새벽</b></div><div class="home-actions">${button("작전 개시", "stage", "primary large", "arrow")}${button("덱 편성", "deck", "ghost", "deck")}</div><p class="build-tag">PLAYABLE ALPHA <span>v0.1 / LOCAL SAVE</span></p></div>
 <aside class="command-panel"><div class="panel-head"><span>COMMAND CENTER</span><span class="live-dot"></span></div><div class="command-status"><small>현재 위협 단계</small><strong>LEVEL <em>01</em></strong><div class="threat-bar"><i></i><i></i><i></i><i></i><i></i></div><p>제7구역에서 균열 반응이 감지되었습니다.</p></div><button class="mission-tile" data-action="stage"><div class="mission-map">${icon("shield")}<span>SECTOR 07</span></div><small>STORY OPERATION</small><h3>침묵의 교차로 ${icon("chevron")}</h3><p>30 WAVES <span>·</span> 2 BOSSES</p></button><div class="operation-progress"><span>최고 기록</span><b>${String(s.bestWave).padStart(2, "0")} <small>/ 30</small></b></div><div class="mini-progress"><i style="width:${(s.bestWave / 30) * 100}%"></i></div><div class="dispatch-note">${icon("info")}<span>육성은 강함을, 전략은 승률을.<br>그리고 운은 한 판을 뒤집습니다.</span></div></aside>
 </section>`;
}
export function heroScreen(s: SaveData, id: string) {
  const h = heroById[id],
    p = s.heroes[id];
  return `<section class="collection-screen"><div class="section-heading"><div><span class="eyebrow">OPERATOR ARCHIVE</span><h1>요원 기록 <small>10 / 10</small></h1></div><span class="muted">당신의 가능성을 함께할 요원들</span></div><div class="collection-layout"><div class="hero-grid">${heroes.map((v) => heroCard(v, s, v.id === id)).join("")}</div><aside class="hero-detail" style="--hero-color:${h.color}"><div class="detail-portrait">${portrait(id)}<span>${h.code}</span></div><div class="detail-body"><small class="eyebrow">${h.rarity.toUpperCase()} / ${h.role}</small><h2>${h.name} <span>Lv.${p.level}</span></h2><p>${h.description}</p><div class="stats-grid"><div><small>ATK</small><b>${Math.round(h.atk * (1 + 0.04 * (p.level - 1)))}</b></div><div><small>HP</small><b>${Math.round(h.hp * (1 + 0.04 * (p.level - 1)))}</b></div><div><small>ASPD</small><b>${h.speed}/s</b></div></div><div class="skill-line">${icon("bolt")}<span>${h.skill}</span></div>${button(p.level >= 50 ? "최대 레벨" : `레벨업 · ${num(p.level * 60)} C`, "hero-upgrade", "primary", "science", `data-id="${id}" ${p.level >= 50 || s.credits < p.level * 60 ? "disabled" : ""}`)}<div class="future-growth"><span>돌파 0</span><span>스킬 Lv.1</span><span>장비 —</span><span>호감도 0</span></div><small class="muted">돌파·스킬·장비·호감도는 후속 버전에서 개방</small><details><summary>전투 합성 성장표</summary>${h.evolution.map((e, i) => `<p>${"★".repeat(i + 1)} ${e.text}</p>`).join("")}</details></div></aside></div></section>`;
}
export function deckScreen(s: SaveData) {
  return `<section class="deck-screen"><div class="section-heading"><div><span class="eyebrow">SQUAD FORMATION</span><h1>출격 덱 편성 <small>${s.deck.length} / 10</small></h1></div>${button("출격 준비", "stage", "primary", "arrow")}</div><div class="deck-info">${icon("info")}<p>선택한 요원만 전투에서 소환됩니다. <strong>덱을 줄이면 합성이 쉬워지고, 넓히면 다양한 시너지를 만들 수 있습니다.</strong></p><span>자동 저장 ${icon("check")}</span></div><div class="deck-grid">${heroes.map((h) => heroCard(h, s, s.deck.includes(h.id), "toggle-deck")).join("")}</div><div class="deck-footer"><span>최소 1명 · 최대 10명 / 같은 단계 3명 → 다음 단계 1명</span><div>${button("전체 선택", "deck-all", "ghost")}${button("추천 5인", "deck-recommended", "ghost")}</div></div></section>`;
}
export function stageScreen(s: SaveData) {
  return `<section class="stage-screen"><div class="section-heading"><div><span class="eyebrow">OPERATION SELECT</span><h1>작전 지역</h1></div><span class="muted">CHAPTER 01 / 첫 번째 균열</span></div><div class="stage-layout"><div class="stage-art"><div class="tactical-grid"></div><div class="map-route"><i>01</i><i>02</i><i>03</i></div><div class="stage-art-caption"><span>NEO SEOUL · EAST DISTRICT</span><h2>SECTOR <em>07</em></h2><p>침묵의 교차로</p></div><span class="stage-coordinate">37°33′ N / 126°58′ E</span></div><aside class="stage-brief"><span class="eyebrow">OPERATION 01 — ${s.cleared ? "CLEARED" : "AVAILABLE"}</span><h2>침묵의 교차로</h2><p>도시를 가로지르는 균열이 열렸습니다.<br>요원을 배치하고, 몰려오는 공허 군단으로부터<br>중앙 코어를 지켜내세요.</p><div class="brief-stats"><div><small>WAVES</small><b>30</b></div><div><small>BOSSES</small><b>02</b></div><div><small>예상 시간</small><b>10–15<small>분</small></b></div></div><div class="boss-brief"><span>10 WAVE</span><b>경계 파괴자</b><small>체력이 낮을수록 이동 가속</small></div><div class="boss-brief"><span>30 WAVE</span><b>영하의 군주</b><small>주기적으로 주변 요원 교란</small></div><div class="squad-preview">${s.deck
    .slice(0, 6)
    .map((id) => portrait(id))
    .join(
      "",
    )}<span>${s.deck.length}명 편성</span></div>${button("전투 시작", "start-battle", "primary large", "battle")}<small class="muted">클리어 보너스 500 C + 처치·웨이브 보상</small></aside></div></section>`;
}
export function resultScreen(r: BattleResult) {
  return `<section class="result-screen ${r.won ? "won" : "lost"}"><span class="eyebrow">OPERATION REPORT / SECTOR 07</span><h1>${r.won ? "VICTORY" : "DEFEAT"}</h1><p>${r.won ? "균열이 닫혔습니다. 도시가 당신을 기억할 것입니다." : "방어선이 무너졌습니다. 다음 작전은 더 강해질 것입니다."}</p><div class="result-layout"><div class="mvp-card">${r.mvp ? portrait(r.mvp) : icon("shield")}<span>MOST VALUABLE OPERATOR</span><h2>${r.mvp ? heroById[r.mvp].name : "출격 대기"}</h2></div><div class="result-stats"><div><small>작전 시간 (게임 시간)</small><b>${time(r.time)}</b></div><div><small>도달 웨이브</small><b>${r.wave} / 30</b></div><div><small>처치 수</small><b>${num(r.kills)}</b></div><div><small>최고 합성</small><b class="stars">${"★".repeat(r.highestStar)}</b></div><div><small>전투 획득 GOLD</small><b>${num(r.gold)}</b></div><div><small>영구 보상 CREDIT</small><b class="mint">+${num(r.credits)}</b></div><div class="result-builds"><small>BUILD RECORD</small><p>${
    Object.entries(r.builds)
      .filter(([, n]) => n)
      .map(
        ([key, n]) =>
          `<span>${buildNames[key as keyof typeof buildNames]} ${n}</span>`,
      )
      .join("") || "기본 전술"
  }</p></div></div></div><div class="result-actions">${button("홈으로", "home", "ghost", "home")}${button("다시 도전", "start-battle", "primary", "arrow")}</div><small class="muted">영구 보상이 저장되었습니다. 전투 합성·특성·유물은 초기화됩니다.</small></section>`;
}
export function settingsScreen(s: SaveData, available: boolean) {
  return `<section class="settings-screen"><div class="section-heading"><div><span class="eyebrow">SYSTEM CONFIGURATION</span><h1>설정</h1></div></div><div class="settings-grid"><div class="settings-panel"><h3>게임 환경</h3>${(["sound", "shake", "lowEffects"] as const).map((key, i) => `<button class="setting-row" data-action="setting" data-id="${key}" aria-pressed="${s.settings[key]}"><span><b>${["효과음", "보스 화면 흔들림", "저사양 효과"][i]}</b><small>${["공격 · 소환 · 합성 · 보스 효과음", "기본 OFF · 짧은 보스 등장 효과", "이펙트 표시를 최대 25개로 제한"][i]}</small></span><i class="toggle ${s.settings[key] ? "on" : ""}"></i></button>`).join("")}<h3>튜토리얼</h3><p class="muted">첫 소환부터 특성 선택까지, 여섯 단계의 작전 안내.</p>${button("다음 전투에서 튜토리얼 다시 보기", "tutorial-reset", "ghost", "info")}</div><div class="settings-panel"><h3>저장 데이터 <span class="status-label">${available ? "LOCAL SAVE" : "저장 불가 · 백업 필요"}</span></h3><p class="muted">이 브라우저에 자동 저장됩니다. 다른 기기로 이동할 때 저장 파일을 내보낸 뒤 가져오세요. 서버 동기화는 지원하지 않습니다.</p><div class="save-facts"><span>저장 버전 <b>1</b></span><span>출격 횟수 <b>${s.runs}</b></span><span>최고 기록 <b>${s.bestWave} WAVE</b></span></div>${button("저장 파일 내보내기", "export", "ghost", "download")}${button("저장 파일 가져오기", "import", "ghost", "deck")}<input type="file" id="save-file" accept="application/json,.json" hidden/><h3>조작 방법</h3><p class="muted">클릭 / 터치: 요원 선택<br>드래그 또는 요원 → 빈 슬롯 클릭: 이동<br>SPACE: 랜덤 소환 · M: 가능한 합성<br>ESC: 일시정지 · 1 / 2: 게임 속도<br>대기석 요원 선택 → 전장 슬롯: 배치</p></div></div></section>`;
}
