import { battleMaps } from "../data/map";
import { heroes, heroById, buildNames, gradeNames, heroElementName } from "../data/heroes";
import {dealerFirst,formationRole,formationRoleName,formationSort} from "../data/combatRoles";
import {heroCollectionFilter} from './CampaignUI';
import type { SaveData } from "../data/types";
import type { BattleResult } from "../systems/BattleModel";
import { button, combatPortrait, heroCard, icon, num, portrait, time } from "./components";
import {armorCatalog,enhanceCost,equipped,equipmentBonus,equipmentCraftCost,equipmentSalvageValue,equipmentShopPrice,heroWeaponGroup,makeEquipment,necklaceCatalog,rarityMax,weaponCatalog,weaponGroupNames} from '../data/equipment';
import type {EquipmentSlot} from '../data/equipment';
import type {HeroGrade} from '../data/types';
import {RECRUIT_COST,RECRUIT_RATES,RECRUIT_S_PITY,recruitDisplayGrade,type RecruitResult} from '../systems/RecruitSystem';
import {commanders,commanderPortrait} from '../data/commanders';
import {assetUrl} from '../utils/assets';
export function home(s: SaveData) {
  return `<section class="home-screen">
 <div class="city-scene" aria-hidden="true"><div class="city-grid"></div><div class="rift-ring"></div><div class="city-buildings">${Array.from({ length: 18 }, (_, i) => `<i style="--h:${22 + ((i * 29) % 61)}%;--w:${25 + ((i * 17) % 35)}px"></i>`).join("")}</div><div class="ground-grid"></div></div>
 <div class="hero-art"><span class="orbit one"></span><span class="orbit two"></span>${portrait("sera", "featured")}<div class="character-caption"><span>OPERATOR / 05</span><b>세라 <small>SERA</small></b><p>“지휘관, 사선은 제가 확보할게요.”</p></div></div>
 <div class="home-copy"><span class="eyebrow"><i class="live-dot"></i> RIFT RESPONSE DIVISION</span><h1>BEYOND<br>THE <em>RIFT.</em></h1><p class="home-subtitle">균열 너머의 위협.<br>당신만의 작전으로 돌파하세요.</p><div class="chapter-label"><span>CHAPTER 01</span><b>청록 연구시설의 균열</b></div><div class="home-actions">${button("작전 개시", "stage", "primary large", "arrow")}${button("실전 배치", "campaign-deploy", "ghost", "deck")}</div><p class="build-tag">PLAYABLE ALPHA <span>v0.1 / LOCAL SAVE</span></p></div>
 <aside class="command-panel"><div class="panel-head"><span>COMMAND CENTER</span><span class="live-dot"></span></div><div class="command-status"><small>현재 위협 단계</small><strong>LEVEL <em>01</em></strong><div class="threat-bar"><i></i><i></i><i></i><i></i><i></i></div><p>연구시설에서 균열 반응이 감지되었습니다.</p></div><button class="mission-tile" data-action="stage"><div class="mission-map">${icon("shield")}<span>AREA 01–12</span></div><small>STORY OPERATION</small><h3>균열 원정 ${icon("chevron")}</h3><p>120 STAGES <span>·</span> 5 OPERATORS</p></button><div class="operation-progress"><span>최고 기록</span><b>${String(s.bestWave).padStart(2, "0")} <small>WAVE</small></b></div><div class="mini-progress"><i style="width:${Math.min(100, s.bestWave)}%"></i></div><div class="dispatch-note">${icon("info")}<span>육성은 강함을, 전략은 승률을.<br>그리고 운은 한 판을 뒤집습니다.</span></div></aside>
 </section>`;
}
export function heroScreen(s: SaveData, id: string) {
  const h = heroById[id],
    p = s.heroes[id],gear=equipped(s,id),bonus=equipmentBonus(s,id),starCost=[0,0,5,10,20,35][p.stars+1]??999,fragments=s.campaign?.fragments[id]??0;
  const slot=(kind:'weapon'|'armor'|'necklace',label:string)=>{const item=gear.find(v=>v.slot===kind);return `<div class="equip-slot ${item?'filled':''}"><span class="equipment-icon ${kind} ${item?.weaponGroup??item?.element??item?.templateId??''}"></span><span><small>${label}</small><b>${item?`${item.name} · ${item.rarity} +${item.enhance}`:'비어 있음'}</b>${item?`<em>ATK +${Math.round(item.attack*(1+item.enhance*.05))} · HP +${Math.round(item.hp*(1+item.enhance*.05))}</em>`:''}</span>${item?button(item.enhance>=rarityMax[item.rarity]?'MAX':'강화','equipment-enhance','compact','',`data-id="${item.id}" ${item.enhance>=rarityMax[item.rarity]?'disabled':''}`)+button('해제','equipment-unequip','compact','',`data-id="${item.id}"`):''}</div>`;};
  const usable=s.equipmentInventory.filter(v=>!v.equippedBy&&(v.slot!=='weapon'||v.weaponGroup===heroWeaponGroup[id])).sort((a,b)=>['SR','S','A','B'].indexOf(a.rarity)-['SR','S','A','B'].indexOf(b.rarity)||b.enhance-a.enhance);
  return `<section class="collection-screen equipment-screen"><div class="section-heading compact"><div><span class="eyebrow">OPERATOR / EQUIPMENT</span><h1>요원·장비 <small>${s.equipmentInventory.length}/100</small></h1></div><span class="muted">강화 재료 ${s.equipmentMaterials}</span></div><div class="hero-collection-tools"><label>포지션 <select id="hero-role-filter">${[['all','전체'],['tank','탱커'],['dealer','딜러'],['sniper','저격수'],['support','서포터']].map(([v,n])=>`<option value="${v}" ${heroCollectionFilter.role===v?'selected':''}>${n}</option>`).join('')}</select></label><label>등급 <select id="hero-grade-filter">${['all','B','A','S','SR'].map(v=>`<option value="${v}" ${heroCollectionFilter.grade===v?'selected':''}>${v==='all'?'전체':v}</option>`).join('')}</select></label><small>포지션 → 등급 → 이름순</small></div><div class="collection-layout"><div class="hero-grid">${[...heroes].sort(formationSort).map((v) => `<div data-hero-card data-role="${formationRole(v.id)}" data-grade="${v.grade}">${heroCard(v, s, v.id === id)}</div>`).join("")}</div><aside class="hero-detail" style="--hero-color:${h.color}"><div class="detail-portrait">${portrait(id)}<span>${h.code}</span></div><div class="detail-body"><small class="eyebrow">${gradeNames[h.grade]} / ${formationRoleName[formationRole(id)]} / ${heroElementName(h)}</small><h2>${h.name} <span>${'★'.repeat(p.stars)}</span></h2><p>${h.description}</p><div class="stats-grid"><div><small>ATK</small><b>${Math.round((h.atk+bonus.attack)*(1+.08*(p.stars-1))*(1+bonus.elementDamage))}</b></div><div><small>HP</small><b>${Math.round((h.hp+bonus.hp)*(1+.08*(p.stars-1)))}</b></div><div><small>추가 속성</small><b>${bonus.element?`${bonus.element} ${Math.round(bonus.elementDamage*100)}%`:'없음'}</b></div></div><div class="skill-line">${icon("bolt")}<span>${h.skill}</span></div>${button(p.stars>=5?'최대 승급':`별 승급 · 조각 ${starCost}`, 'hero-star','primary','science',`data-id="${id}" ${p.stars>=5||fragments<starCost?'disabled':''}`)}<small>보유 조각 ${fragments} · 레벨 격차 없이 장비와 별로 성장합니다.</small><div class="equipment-slots">${slot('weapon','무기')}${slot('armor','갑옷')}${slot('necklace','목걸이')}</div>${button('추천 장비 자동 장착','equipment-auto','ghost','settings',`data-id="${id}"`)}<details><summary>가방 열기 · 장착 가능한 장비 ${usable.length}개</summary><div class="equipment-list">${usable.slice(0,30).map(v=>`<article class="equipment-item grade-${v.rarity}"><span class="equipment-icon ${v.slot} ${v.weaponGroup??v.element??''}"></span><span><b>${v.name} · ${v.rarity} +${v.enhance}</b><small>${v.effect}${v.element?` · ${v.element} 추가 ${Math.round(v.elementDamage*100)}%`:''}</small></span>${button('장착','equipment-equip','compact','',`data-id="${v.id}"`)}${button(v.enhance>=rarityMax[v.rarity]?'MAX':'강화','equipment-enhance','compact','',`data-id="${v.id}" ${v.enhance>=rarityMax[v.rarity]?'disabled':''}`)}</article>`).join('')||'<p class="muted">사용 가능한 장비가 없습니다. 캠페인에서 획득하세요.</p>'}</div></details></div></aside></div></section>`;
}
export function deckScreen(s: SaveData) {
  return `<section class="deck-screen"><div class="section-heading"><div><span class="eyebrow">SQUAD FORMATION</span><h1>출격 덱 편성 <small>${s.deck.length} / 10</small></h1></div>${button("출격 준비", "stage", "primary", "arrow")}</div><div class="deck-info">${icon("info")}<p>전투에서는 영웅을 직접 선택해 정가로 구매합니다. <strong>영웅마다 가격이 다르며 같은 영웅을 반복 구매하면 가격이 오릅니다. 구매 목록은 딜러 우선, 서포터 하단 순서입니다.</strong><br>속성 연계: 물+전기=전도 · 불+전기=과부하 · 물+불=증발 · 어둠+불=흑염 · 어둠+물=침식 · 어둠+전기=공허 감전</p><span>자동 저장 ${icon("check")}</span></div><div class="deck-grid">${[...heroes].sort(dealerFirst).map((h) => heroCard(h, s, s.deck.includes(h.id), "toggle-deck")).join("")}</div><div class="deck-footer"><span>최소 1명 · 최대 10명 / 같은 별 2명 → 다음 단계 1명</span><div>${button("B급 10명", "deck-all", "ghost")}${button("A급 5인", "deck-recommended", "ghost")}${button("S급 4인", "deck-s", "ghost")}${button("SR 2인", "deck-sr", "ghost")}</div></div></section>`;
}
export function equipmentShop(s:SaveData,rarity:HeroGrade,slot:'weapon'|'armor'|'necklace'='weapon',weaponGroup='rifle'){
 const catalog=slot==='weapon'?weaponCatalog.filter(v=>v.weaponGroup===weaponGroup):slot==='armor'?armorCatalog:necklaceCatalog,price=equipmentShopPrice[rarity];
 return `<section class="equipment-shop-screen"><div class="section-heading compact"><div><span class="eyebrow">SALVAGE EXCHANGE</span><h1>장비 상점</h1></div><div class="shop-wallet"><small>보유 골드</small><b>${num(s.equipmentGold)} G</b></div></div><div class="equipment-shop-steps"><nav aria-label="장비 부위">${([['weapon','무기'],['armor','갑옷'],['necklace','목걸이']] as const).map(([id,label])=>button(label,'equipment-shop-slot',slot===id?'primary':'ghost','',`data-id="${id}"`)).join('')}</nav><nav class="equipment-shop-rarities" aria-label="장비 등급">${(['B','A','S','SR'] as HeroGrade[]).map(v=>button(`${v} · ${equipmentShopPrice[v]}G`,'equipment-shop-rarity',v===rarity?'primary':'ghost','',`data-id="${v}"`)).join('')}</nav>${slot==='weapon'?`<label class="weapon-family"><span>무기 종류</span><select id="equipment-shop-group">${Object.entries(weaponGroupNames).map(([id,name])=>`<option value="${id}" ${id===weaponGroup?'selected':''}>${name}</option>`).join('')}</select></label>`:''}</div><div class="shop-selection-summary"><b>${slot==='weapon'?weaponGroupNames[weaponGroup as keyof typeof weaponGroupNames]:slot==='armor'?'갑옷':'속성 목걸이'} · ${rarity}</b><small>구매 후 출전 준비에서 장착</small></div><div class="equipment-shop-grid">${catalog.map(v=>{const item=makeEquipment(v.id,rarity,0,'preview'),kind=item.weaponGroup??item.element??item.templateId;return `<article class="equipment-shop-card grade-${rarity}"><span class="equipment-icon ${item.slot} ${kind}"></span><div><b>${item.name}</b><p>${item.effect}${item.attack?` · ATK +${item.attack}`:''}${item.hp?` · HP +${item.hp}`:''}${item.element?` · 추가 피해 ${Math.round(item.elementDamage*100)}%`:''}</p></div>${button(`${price}G`,'equipment-shop-buy','compact','',`data-id="${item.templateId}" ${s.equipmentGold<price||s.equipmentInventory.length>=100?'disabled':''}`)}</article>`;}).join('')}</div></section>`;
}
export function itemScreen(s:SaveData,tab:'inventory'|'craft'|'equipped',slot:'all'|EquipmentSlot,rarity:'all'|HeroGrade,selectedId:string|undefined,craftRarity:HeroGrade,craftSlot:EquipmentSlot,weaponGroup:string,salvageGrades:ReadonlySet<HeroGrade>=new Set()){
 const salvageTargets=s.equipmentInventory.filter(v=>salvageGrades.has(v.rarity)&&!v.equippedBy&&!v.locked&&!Object.values(s.heroes).some(h=>h.equipment.includes(v.id)));
 const salvageControls=`<div class="item-salvage-controls" role="group" aria-label="일괄 분해 등급"><span>분해 등급</span>${(['B','A','S','SR'] as HeroGrade[]).map(g=>`<label><input type="checkbox" data-salvage-grade="${g}" ${salvageGrades.has(g)?'checked':''}>${g}</label>`).join('')}${button(salvageGrades.size===4?'전체 해제':'전체 선택','item-salvage-all','ghost')}${button(`${salvageTargets.length}개 분해 · 재료 +${salvageTargets.reduce((n,v)=>n+equipmentSalvageValue(v),0)}`,'item-salvage-selected','danger','',salvageTargets.length?'':'disabled')}<small>장착·잠금 장비 제외 · 보관함 전체 기준</small></div>`;
 const gradeRank={SR:0,S:1,A:2,B:3},slotName={weapon:'무기',armor:'갑옷',necklace:'목걸이'},items=s.equipmentInventory.filter(v=>(slot==='all'||v.slot===slot)&&(rarity==='all'||v.rarity===rarity)).sort((a,b)=>gradeRank[a.rarity]-gradeRank[b.rarity]||b.enhance-a.enhance||a.name.localeCompare(b.name));
 const selected=s.equipmentInventory.find(v=>v.id===selectedId)??items[0],owner=selected?.equippedBy?heroById[selected.equippedBy]:undefined;
 const templates=craftSlot==='weapon'?weaponCatalog.filter(v=>v.weaponGroup===weaponGroup):craftSlot==='armor'?armorCatalog:necklaceCatalog,cost=equipmentCraftCost[craftRarity];
 const itemRow=(v:typeof s.equipmentInventory[number])=>`<button class="item-vault-row grade-${v.rarity} ${selected?.id===v.id?'selected':''}" data-action="item-select" data-id="${v.id}"><span class="equipment-icon ${v.slot} ${v.weaponGroup??v.element??v.templateId}"></span><span><b>${v.name}</b><small>${v.rarity} · +${v.enhance} · ${slotName[v.slot]}${v.equippedBy?` · ${heroById[v.equippedBy]?.name??'장착 중'}`:''}</small></span><em>${v.locked?'잠금':v.equippedBy?'장착':'보관'}</em></button>`;
 const detail=selected?`<aside class="item-detail grade-${selected.rarity}"><div class="item-detail-title"><span class="equipment-icon ${selected.slot} ${selected.weaponGroup??selected.element??selected.templateId}"></span><div><small>${selected.rarity} · ${slotName[selected.slot]}</small><h2>${selected.name} <em>+${selected.enhance}</em></h2></div></div><p>${selected.effect}</p><div class="item-stat-grid"><span>공격력 <b>+${Math.round(selected.attack*(1+selected.enhance*.05))}</b></span><span>체력 <b>+${Math.round(selected.hp*(1+selected.enhance*.05))}</b></span><span>공속 <b>+${Math.round(selected.speed*100)}%</b></span><span>치명 <b>+${Math.round(selected.crit*100)}%</b></span></div><div class="item-owner">${owner?`${portrait(owner.id)}<span><small>장착 요원</small><b>${owner.name}</b></span>`:'<span><small>장착 요원</small><b>보관 중</b></span>'}</div><div class="item-actions">${button(selected.enhance>=5?'강화 MAX':`강화 · ${Math.ceil(enhanceCost(selected).gold)}C / 재료 ${enhanceCost(selected).material}`,'equipment-enhance','primary','',`data-id="${selected.id}" ${selected.enhance>=5?'disabled':''}`)}${owner?button('장착 해제','equipment-unequip','ghost','',`data-id="${selected.id}"`):button(selected.locked?'잠금 해제':'잠금','equipment-lock','ghost','',`data-id="${selected.id}"`)}${!owner&&!selected.locked?button(`분해 · 재료 +${equipmentSalvageValue(selected)}`,'equipment-salvage','danger','',`data-id="${selected.id}"`):''}</div></aside>`:'<aside class="item-detail empty"><p>장비를 선택해주세요.</p></aside>';
 const inventory=`<div class="item-workspace"><div class="item-vault">${items.map(itemRow).join('')||'<p class="empty-state">조건에 맞는 장비가 없습니다.</p>'}</div>${detail}</div>`;
 const craft=`<div class="craft-layout"><section class="craft-controls"><h2>확정 제작</h2><p>원하는 장비를 직접 제작합니다. 무작위 결과가 나오지 않습니다.</p><div class="craft-options"><nav>${(['weapon','armor','necklace'] as EquipmentSlot[]).map(v=>button(slotName[v],'item-craft-slot',v===craftSlot?'primary':'ghost','',`data-id="${v}"`)).join('')}</nav><nav>${(['B','A','S','SR'] as HeroGrade[]).map(v=>button(v,'item-craft-rarity',v===craftRarity?'primary':'ghost','',`data-id="${v}"`)).join('')}</nav>${craftSlot==='weapon'?`<label>무기 종류<select id="item-craft-group">${Object.entries(weaponGroupNames).map(([id,name])=>`<option value="${id}" ${id===weaponGroup?'selected':''}>${name}</option>`).join('')}</select></label>`:''}</div><div class="craft-cost"><span>필요 재료 <b>${cost.material}</b></span><span>전리품 골드 <b>${cost.gold}G</b></span></div></section><section class="craft-list">${templates.map(v=>{const p=makeEquipment(v.id,craftRarity,0,'craft-preview');return `<article class="craft-card grade-${craftRarity}"><span class="equipment-icon ${p.slot} ${p.weaponGroup??p.element??p.templateId}"></span><span><b>${p.name}</b><small>${p.effect}${p.attack?` · ATK +${p.attack}`:''}${p.hp?` · HP +${p.hp}`:''}</small></span>${button('제작','item-craft','compact','',`data-id="${p.templateId}" ${s.equipmentMaterials<cost.material||s.equipmentGold<cost.gold||s.equipmentInventory.length>=100?'disabled':''}`)}</article>`;}).join('')}</section></div>`;
 const equippedItems=s.equipmentInventory.filter(v=>v.equippedBy).sort((a,b)=>(heroById[a.equippedBy!]?.name??'').localeCompare(heroById[b.equippedBy!]?.name??'')||a.slot.localeCompare(b.slot));
 const equippedView=`<div class="equipped-overview">${equippedItems.map(v=>`<article>${portrait(v.equippedBy!)}<span><b>${heroById[v.equippedBy!]?.name}</b><small>${slotName[v.slot]} · ${v.name} · ${v.rarity} +${v.enhance}</small></span>${button('보기','item-select','compact','',`data-id="${v.id}"`)}</article>`).join('')||'<p class="empty-state">장착 중인 장비가 없습니다.</p>'}</div>`;
 return `<section class="item-screen"><header class="item-head"><div><span class="eyebrow">ARMORY / WORKSHOP</span><h1>아이템</h1></div><div class="item-wallet"><span>보관 <b>${s.equipmentInventory.length}/100</b></span><span>재료 <b>${s.equipmentMaterials}</b></span><span>골드 <b>${num(s.equipmentGold)}G</b></span></div></header><nav class="item-tabs">${button('보관함','item-tab',tab==='inventory'?'primary':'ghost','',`data-id="inventory"`)}${button('제작','item-tab',tab==='craft'?'primary':'ghost','',`data-id="craft"`)}${button('장착 현황','item-tab',tab==='equipped'?'primary':'ghost','',`data-id="equipped"`)}</nav>${tab==='inventory'?`<div class="item-filters"><select id="item-filter-slot"><option value="all">모든 부위</option>${Object.entries(slotName).map(([v,n])=>`<option value="${v}" ${slot===v?'selected':''}>${n}</option>`).join('')}</select><select id="item-filter-rarity"><option value="all">모든 등급</option>${['B','A','S','SR'].map(v=>`<option value="${v}" ${rarity===v?'selected':''}>${v}</option>`).join('')}</select></div>${salvageControls}${inventory}`:tab==='craft'?craft:equippedView}</section>`;
}
export function recruitScreen(s:SaveData){const featured=heroes.filter(h=>h.grade==='SR').slice(0,3);return `<section class="recruit-screen"><div class="recruit-banner"><div class="recruit-copy"><span class="eyebrow">RIFT RESONANCE / LIMITED BANNER</span><h1>균열 공명 모집</h1><p>균열 신호를 추적해 요원을 모집합니다. 중복 요원은 별 승급 조각으로 전환됩니다.</p><div class="recruit-featured">${featured.map(h=>`<span>${combatPortrait(h.id)}<b>${h.name}</b><small>SSR</small></span>`).join('')}</div></div><div class="recruit-art">${portrait(featured[0].id,'featured')}</div></div><div class="recruit-status"><span>보유 골드 <b>${num(s.equipmentGold)}G</b></span><span>S 이상 확정 <b>${RECRUIT_S_PITY-s.recruitPity}회 이내</b></span><span>누적 모집 <b>${s.recruitCount}</b></span></div><div class="recruit-actions">${button(`1회 모집 · ${RECRUIT_COST.one}G`,'recruit-pull','ghost','gem',`data-id="1" ${s.equipmentGold<RECRUIT_COST.one?'disabled':''}`)}${button(`10회 모집 · ${RECRUIT_COST.ten}G`,'recruit-pull','primary','gem',`data-id="10" ${s.equipmentGold<RECRUIT_COST.ten?'disabled':''}`)}</div><div class="recruit-rates">${Object.entries(RECRUIT_RATES).map(([g,n])=>`<span><b>${recruitDisplayGrade(g as HeroGrade)}</b><small>${n}%</small></span>`).join('')}<p>10회 모집 시 A 이상 1명 확정 · 30회 안에 S 이상 확정 · 확정 발동 후 천장 초기화</p></div></section>`;}
export function recruitResult(results:RecruitResult[]){const best=results.some(v=>v.grade==='SR')?'ssr':results.some(v=>v.grade==='S')?'s':'normal';return `<div class="modal recruit-result-modal tier-${best}" role="dialog" aria-label="모집 결과"><div class="recruit-flare" aria-hidden="true"><i></i><i></i><i></i></div><header><span class="eyebrow">RESONANCE COMPLETE</span><h2>${best==='ssr'?'SSR 공명 폭발':best==='s'?'황금 공명':'요원 모집 완료'}</h2></header><div class="recruit-result-grid count-${results.length}">${results.map((v,i)=>`<article class="recruit-result-card grade-${v.grade}" style="--delay:${i*70}ms"><div>${combatPortrait(v.hero.id)}<span>${v.displayGrade}</span></div><b>${v.hero.name}</b><small>${v.newHero?'NEW 요원 획득':`중복 · 조각 +${v.fragments}`}</small></article>`).join('')}</div>${button('확인','close-modal','primary large')}</div>`;}
export function stageScreen(s: SaveData) {
 return `<section class="stage-screen"><div class="section-heading"><div><span class="eyebrow">OPERATION SELECT</span><h1>연구시설 방어</h1></div></div><p>소환 등급을 선택한 뒤 빈 배치 칸을 누르면 해당 등급 요원이 소환됩니다. 배치한 요원은 이동하거나 10초 안에 배치를 되돌릴 수 있습니다.</p><div class="remake-map-grid">${battleMaps.map((m,i)=>`<article class="remake-map-card"><span class="eyebrow">SECTOR 0${i+1}</span><svg viewBox="0 0 800 800" role="img" aria-label="${m.name} 이동 경로"><rect width="800" height="800" fill="#122330"/>${m.slots.map(s=>`<rect x="${s.x-17}" y="${s.y-17}" width="34" height="34" fill="#315349"/>`).join('')}<polyline points="${m.path.map(p=>`${p.x},${p.y}`).join(' ')}" fill="none" stroke="#99dbed" stroke-width="25"/>${m.obstacles.map(o=>`<rect x="${o.x-22}" y="${o.y-22}" width="44" height="44" fill="#ba9462"/>`).join('')}</svg><h2>${m.name}</h2><p>${m.description}</p><small>배치 가능 ${m.slots.length}칸 · 무한 웨이브 · 요원 최대 22명</small>${button('이 지역에서 시작','start-battle','primary','battle',`data-id="${m.id}"`)}</article>`).join('')}</div></section>`;
}
export function resultScreen(r: BattleResult) {
  return `<section class="modal battle-result-modal result-screen ${r.won ? "won" : "lost"}"><span class="eyebrow">OPERATION REPORT / LAB 01</span><h1>RUN OVER</h1><p>방어선이 무너졌습니다. 기록을 갱신하고 더 높은 웨이브에 도전하세요.</p><div class="result-layout"><div class="mvp-card">${r.mvp ? portrait(r.mvp) : icon("shield")}<span>MOST VALUABLE OPERATOR</span><h2>${r.mvp ? heroById[r.mvp].name : "출격 대기"}</h2></div><div class="result-stats"><div><small>작전 시간 (게임 시간)</small><b>${time(r.time)}</b></div><div><small>도달 웨이브</small><b>${r.wave}</b></div><div><small>처치 수</small><b>${num(r.kills)}</b></div><div><small>최고 합성</small><b class="stars">${"★".repeat(r.highestStar)}</b></div><div><small>전투 획득 GOLD</small><b>${num(r.gold)}</b></div><div><small>영구 보상 CREDIT</small><b class="mint">+${num(r.credits)}</b></div><div class="result-builds"><small>BUILD RECORD</small><p>${
    Object.entries(r.builds)
      .filter(([, n]) => n)
      .map(
        ([key, n]) =>
          `<span>${buildNames[key as keyof typeof buildNames]} ${n}</span>`,
      )
      .join("") || "기본 전술"
  }</p></div><div class="result-builds"><small>ELEMENT REACTIONS</small><p>${
    Object.entries(r.reactions)
      .filter(([, n]) => n)
      .sort((a, b) => b[1] - a[1])
      .slice(0, 4)
      .map(([key, n]) => `<span>${({ conduct: "전도", overload: "과부하", vaporize: "증발", blackflame: "흑염", corrosion: "침식", voidshock: "공허 감전" } as Record<string, string>)[key] ?? key} ${n}</span>`)
      .join("") || "반응 없음"
  }</p></div></div></div><div class="dps-panel open"><b>요원 전투 기록 · 종료 시점 최근 10초 DPS</b>${(r.ranking??[]).map(u=>`<div class="dps-row"><span>${heroById[u.heroId].name} ${"★".repeat(u.star)}</span><b>${u.dps.toFixed(1)}</b><span>${u.kills}킬</span><span>${num(u.damage)}</span></div>`).join("")}</div><section class="strategy-results"><h3>전략 기록</h3><p>사용 ${r.strategy?.spent??0}G · 잔액 ${r.strategy?.remaining??0}G</p><p>투자: ${r.strategy?.investments.slice(0,5).map(v=>heroById[v.heroId].name+" "+v.gold+"G").join(" · ")||"없음"}</p><p>상위 조합: ${Object.entries(r.strategy?.triples??{}).map(([k,v])=>k+" "+v+"회").join(" · ")||"없음"}</p><p>편성 링크: ${Object.entries(r.strategy?.links??{}).map(([k,v])=>k+" "+v+"회").join(" · ")||"없음"}</p><p>처치 순위: ${r.ranking?.slice().sort((a,b)=>b.kills-a.kills).slice(0,5).map(v=>heroById[v.heroId].name+" "+v.kills).join(" · ")}</p><p>지원·제어: ${r.strategy?.support.slice(0,5).map(v=>heroById[v.heroId].name+" 저지 "+v.block.toFixed(1)+"초 / 감속 "+v.slow.toFixed(1)+"초 / 간접 피해(추정) "+Math.round(v.damage)).join(" · ")}</p></section><div class="result-actions">${button("홈으로", "home", "ghost", "home")}${button("다시 도전", "start-battle", "primary", "arrow")}</div><small class="muted">영구 보상이 저장되었습니다. 전투 합성·특성·유물은 초기화됩니다.</small></section>`;
}
export function settingsScreen(s: SaveData, available: boolean) {
  const toggle=(key:'sound'|'bgm'|'sfx'|'shake'|'lowEffects',title:string,description:string)=>`<button class="setting-row" data-action="setting" data-id="${key}" aria-pressed="${s.settings[key]}"><span><b>${title}</b><small>${description}</small></span><i class="toggle ${s.settings[key]?'on':''}"></i></button>`;
  const volume=(key:'bgmVolume'|'sfxVolume',title:string,preview:'bgm'|'sfx')=>{const value=Math.round(s.settings[key]*100),id=`audio-${key}`;return `<div class="audio-volume-row"><label for="${id}"><b>${title}</b><small>0% 음소거 · 100% 최대</small></label><input id="${id}" data-audio-volume="${key}" type="range" min="0" max="100" step="1" value="${value}" aria-label="${title}"><output for="${id}">${value}%</output>${button('미리 듣기','audio-preview','compact','sound',`data-id="${preview}" ${!s.settings.sound||!(preview==='bgm'?s.settings.bgm:s.settings.sfx)?'disabled':''}`)}</div>`};
  return `<section class="settings-screen"><div class="section-heading"><div><span class="eyebrow">SYSTEM CONFIGURATION</span><h1>설정</h1></div></div><div class="settings-grid"><div class="settings-panel audio-settings"><h3>오디오</h3>${toggle('sound','전체 오디오','배경음과 효과음을 한 번에 켜거나 끕니다.')}${toggle('bgm','배경음','메뉴·편성·모집 배경 트랙을 재생합니다.')}${volume('bgmVolume','배경음 볼륨','bgm')}${toggle('sfx','효과음','공격·스킬·피격·UI 효과음을 재생합니다.')}${volume('sfxVolume','효과음 볼륨','sfx')}<h3>게임 환경</h3>${toggle('shake','보스 화면 흔들림','짧은 보스 등장 효과를 표시합니다.')}${toggle('lowEffects','저사양 효과','이펙트를 최대 18개로 제한하고 자동 성능 조절을 사용합니다.')}</div><div class="settings-panel"><h3>저장 데이터 <span class="status-label">${available?'LOCAL SAVE':'저장 불가 · 백업 필요'}</span></h3><p class="muted">설정은 즉시 저장됩니다. 다른 기기로 이동할 때 저장 파일을 내보낸 뒤 가져오세요.</p><div class="save-facts"><span>저장 버전 <b>1</b></span><span>출격 횟수 <b>${s.runs}</b></span><span>최고 기록 <b>${s.bestWave} WAVE</b></span></div>${button('저장 파일 내보내기','export','ghost','download')}${button('저장 파일 가져오기','import','ghost','deck')}<input type="file" id="save-file" accept="application/json,.json" hidden/><h3>전투·조작</h3><p class="muted">터치: 선택 또는 배치 · 드래그: 요원 이동<br>ESC: 일시정지 · 숫자 1~4: 전투 배속<br>AUTO 다음: 마지막 배치를 유지해 연속 출격</p>${button('다음 전투에서 안내 다시 보기','tutorial-reset','ghost','info')}</div></div></section>`;
}

export function commanderSettings(s:SaveData){
  return `<section class="commander-picker-screen"><div class="settings-panel commander-settings"><h3>지휘관 선택 <span class="status-label">TEST · 전원 사용 가능</span></h3><p class="muted">여성 지휘관 8명과 남성 지휘관 2명 중 대표 얼굴을 선택합니다.</p><div class="commander-grid">${commanders.map((v,i)=>`<button data-action="commander-select" data-id="${v.id}" class="commander-card ${s.commanderId===v.id?'selected':''}" aria-pressed="${s.commanderId===v.id}"><img src="${assetUrl(commanderPortrait(v.id))}" alt="${v.name} 지휘관 얼굴"><span><b>${v.name}</b><small>${String(i+1).padStart(2,'0')} · ${v.gender==='female'?'여성':'남성'}</small></span></button>`).join('')}</div></div></section>`;
}

