import {test,expect} from '@playwright/test';
test('campaign selection, formation, preparation, movement and unlock',async({page},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/',{waitUntil:'domcontentloaded'});await page.locator('[data-action="stage"]').first().click();
 await page.locator('[data-action="campaign-select"][data-id="1-2"]').click();
 await expect(page.locator('.campaign-stage [data-action="campaign-deploy"]')).toBeDisabled();
 await expect(page.locator('.campaign-stage')).toHaveCount(1);
 await page.screenshot({path:`artifacts/campaign-stages-${info.project.name}.png`,fullPage:true});
 await page.locator('[data-action="campaign-select"][data-id="1-1"]').first().click();
 await page.locator('.campaign-stage [data-action="campaign-deploy"]').click();
 await page.waitForFunction(()=>!!(window as any).rift.game?.scene.getScene('Battle')?.ink);
 const renderDensity=await page.evaluate(()=>{const canvas=document.querySelector('canvas')!;return {backing:canvas.width,css:canvas.getBoundingClientRect().width,dpr:devicePixelRatio};});
 expect(renderDensity.backing/renderDensity.css).toBeGreaterThanOrEqual(Math.min(2,renderDensity.dpr)-.05);
 expect(await page.evaluate(()=>{const m=(window as any).rift.model;return {started:m.started,units:m.units.length,slots:m.map.slots.length};})).toEqual({started:false,units:5,slots:6});
 await expect(page.locator('#shop-shell')).toHaveCount(0);
 await expect(page.locator('.prep-steps [data-action="campaign-prep-step"]')).toHaveCount(0);
 await expect(page.locator('.prep-roster [data-action="campaign-prep-toggle"]')).toHaveCount(8);
 await expect(page.locator('.prep-roster [data-action="campaign-prep-toggle"]:disabled')).toHaveCount(0);
 await page.evaluate(()=>{const a=(window as any).rift;['yuria','sera','reina','karin','arin'].forEach((id,i)=>a.placeCampaignHero(id,i));});
 expect(await page.evaluate(()=>(window as any).rift.model.units.length)).toBe(5);
 const canvas=page.locator('canvas'),box=await canvas.boundingBox();if(!box)throw Error('canvas missing');
 await page.locator('[data-action="campaign-auto-deploy"]').click();
 await expect(page.locator('#campaign-reserve .prep-unit')).toHaveCount(0);
 await expect(page.locator('[data-action="campaign-start"]')).toBeEnabled();
 const selectedUnit=await page.evaluate(()=>{const m=(window as any).rift.model,u=m.units[0];return {x:u.x,y:u.y,name:u.heroId};});
 await canvas.click({position:{x:selectedUnit.x*box.width/800,y:selectedUnit.y*box.height/800}});
 await expect(page.locator('.prep-bag')).toBeVisible();
 await expect(page.locator('.prep-bag-slots .prep-bag-slot')).toHaveCount(3);
 await expect(page.locator('.prep-bag-stats')).toContainText('ATK');
 await page.locator('#prep-equipment-filter').selectOption('weapon');
 await expect(page.locator('#prep-equipment-filter')).toHaveValue('weapon');
 await page.locator('[data-action="campaign-start"]').click();
 const state=await page.evaluate(()=>{const a=(window as any).rift,m=a.model;a.game.loop.stop();const u=m.units[0];m.selected=u.uid;const first=m.move(u.uid,3),second=m.move(u.uid,0);a.updateHud(true);return {first,second,left:u.moveReadyAt-m.time};});
 expect(state).toEqual({first:true,second:false,left:10});
 await expect(page.locator('#selected-growth')).toContainText('이동 10.0초');
 const width=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,inner:innerWidth}));expect(width.scroll).toBeLessThanOrEqual(width.inner+1);
 await page.locator('canvas').scrollIntoViewIfNeeded();
 await page.screenshot({path:`artifacts/campaign-battle-${info.project.name}.png`,fullPage:true});
 await page.evaluate(()=>{const a=(window as any).rift;a.model.finish(true);a.updateHud(true);});
 await expect(page.locator('.modal-backdrop .campaign-result.won')).toBeVisible();
 await expect(page.locator('.battle-screen')).toBeVisible();
 expect(await page.evaluate(()=>({screen:(window as any).rift.screen,rewards:(window as any).rift.save.data.runs}))).toMatchObject({screen:'battle'});
 await page.evaluate(()=>{(window as any).rift.navigate('stage');});await expect(page.locator('[data-action="campaign-select"][data-id="1-2"]').first()).toBeEnabled();
 await page.reload({waitUntil:'domcontentloaded'});await page.evaluate(()=>{(window as any).rift.navigate('stage');});await expect(page.locator('[data-action="campaign-select"][data-id="1-2"]').first()).toBeEnabled();
 expect(errors).toEqual([]);
});
