import {test,expect} from '@playwright/test';
test('roster, exact shop filters, two-person double click, growth choice and result',async({page},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');await page.evaluate(()=>{const a=(window as any).rift;a.save.data.tutorial=true;a.save.persist();});
 await page.locator('[data-action="hero"]').last().click();await expect(page.locator('.hero-card')).toHaveCount(34);
 await page.evaluate(()=>{const a=(window as any).rift;a.begin('laboratory');});await page.waitForFunction(()=>!!(window as any).rift.game?.scene.getScene('Battle')?.ink);
 await page.evaluate(()=>{const a=(window as any).rift;a.game.loop.stop();a.model.started=false;a.model.gold=10000;a.render();});
 await page.locator('.hero-shop-shell > summary').click();
 await page.locator('[data-action="shop-grade"][data-id="ALL"]').click();await expect(page.locator('[data-action="buy-hero"]')).toHaveCount(34);
 await page.locator('[data-action="buy-hero"][data-id="aurora"]').click();
 await page.evaluate(()=>{const app=(window as any).rift,m=app.model;m.summonAt(0);app.updateHud(true);});
 expect(await page.evaluate(()=>(window as any).rift.model.units[0].heroId)).toBe('aurora');
 await expect(page.locator('[data-action="buy-hero"][data-id="aurora"]')).toContainText('486G');
 await page.evaluate(()=>{const a=(window as any).rift,m=a.model;m.units=[];m.records=[];const u=m.addUnit('sera',2);const material=m.addUnit('sera',2);m.selected=u.uid;m.merge(u.uid,material.uid);a.updateHud(true);});
 await expect(page.locator('[data-action="choice"]')).toHaveCount(3);await page.locator('[data-action="choice"]').first().click();
 expect(await page.evaluate(()=>(window as any).rift.model.units[0].branch)).toBeTruthy();
 for(let i=0;i<6;i++)await page.locator('[data-action="skill"]').click();
 expect(await page.evaluate(()=>(window as any).rift.model.selectedUnit.priority)).toBe('auto');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
 await page.evaluate(()=>{const a=(window as any).rift;a.model.finish(false);a.updateHud(true);});
 await expect(page.getByRole('heading',{name:'RUN OVER'})).toBeVisible();await expect(page.locator('.strategy-results')).toContainText('사용');
 await page.screenshot({path:`artifacts/strategy-result-${info.project.name}.png`,fullPage:true});expect(errors).toEqual([]);
});
