// Generated by scripts/build-campaign-budget.mjs from the 30-second combat audit.
export const campaignCombatBudget:Record<string,{attack:number;speed:number;singleDps:number;basicDps:number;crowdDps:number}>={
  "yuria": {
    "attack": 21,
    "speed": 0.9752000000000001,
    "singleDps": 21,
    "basicDps": 21,
    "crowdDps": 63
  },
  "reina": {
    "attack": 29.400000000000002,
    "speed": 1.8868,
    "singleDps": 74.274,
    "basicDps": 58.486,
    "crowdDps": 100.161
  },
  "arin": {
    "attack": 48,
    "speed": 1.0176,
    "singleDps": 56,
    "basicDps": 44.8,
    "crowdDps": 156.472
  },
  "karin": {
    "attack": 24,
    "speed": 2.2048,
    "singleDps": 102.926,
    "basicDps": 63.908,
    "crowdDps": 336.588
  },
  "sera": {
    "attack": 18,
    "speed": 2.5970000000000004,
    "singleDps": 58.184,
    "basicDps": 48.408,
    "crowdDps": 74.088
  },
  "noel": {
    "attack": 78,
    "speed": 0.6148,
    "singleDps": 70.2,
    "basicDps": 46.8,
    "crowdDps": 204.277
  },
  "luna": {
    "attack": 52,
    "speed": 0.8692,
    "singleDps": 53.777,
    "basicDps": 48.187,
    "crowdDps": 194.87
  },
  "mia": {
    "attack": 22,
    "speed": 1.0176,
    "singleDps": 22.733,
    "basicDps": 22.733,
    "crowdDps": 68.2
  },
  "ian": {
    "attack": 24,
    "speed": 1.3568,
    "singleDps": 47.28,
    "basicDps": 31.28,
    "crowdDps": 51.605
  },
  "leon": {
    "attack": 124.69999999999999,
    "speed": 1.1024,
    "singleDps": 169.642,
    "basicDps": 169.642,
    "crowdDps": 508.926
  },
  "adela": {
    "attack": 70.76,
    "speed": 1.2189999999999999,
    "singleDps": 94.347,
    "basicDps": 87.271,
    "crowdDps": 220.291
  },
  "neris": {
    "attack": 46.36,
    "speed": 0.9964,
    "singleDps": 46.36,
    "basicDps": 46.36,
    "crowdDps": 139.08
  },
  "belka": {
    "attack": 78.08,
    "speed": 0.9540000000000001,
    "singleDps": 103.18,
    "basicDps": 95.372,
    "crowdDps": 356.388
  },
  "serin": {
    "attack": 64.56240000000001,
    "speed": 1.1448,
    "singleDps": 92.927,
    "basicDps": 85.567,
    "crowdDps": 92.927
  },
  "kyle": {
    "attack": 37.82,
    "speed": 1.3144,
    "singleDps": 95.3,
    "basicDps": 54.328,
    "crowdDps": 129.429
  },
  "livia": {
    "attack": 96.10000000000001,
    "speed": 0.9752000000000001,
    "singleDps": 96.1,
    "basicDps": 96.1,
    "crowdDps": 288.3
  },
  "kairon": {
    "attack": 144.89400000000003,
    "speed": 1.0176,
    "singleDps": 196.389,
    "basicDps": 181.9,
    "crowdDps": 676.104
  },
  "theria": {
    "attack": 114.7,
    "speed": 1.3992000000000002,
    "singleDps": 172.05,
    "basicDps": 160.58,
    "crowdDps": 617.496
  },
  "noxia": {
    "attack": 152.76800000000003,
    "speed": 1.0388,
    "singleDps": 207.255,
    "basicDps": 174.41,
    "crowdDps": 769.569
  },
  "aurora": {
    "attack": 176.55456,
    "speed": 1.272,
    "singleDps": 374.242,
    "basicDps": 321.275,
    "crowdDps": 1625.756
  },
  "arden": {
    "attack": 155.00124,
    "speed": 1.1024,
    "singleDps": 398.699,
    "basicDps": 348.943,
    "crowdDps": 1295.607
  },
  "hana": {
    "attack": 46.36,
    "speed": 0.9540000000000001,
    "singleDps": 44.815,
    "basicDps": 44.815,
    "crowdDps": 134.444
  },
  "zion": {
    "attack": 75.64,
    "speed": 0.7632,
    "singleDps": 99.581,
    "basicDps": 76.889,
    "crowdDps": 271.122
  },
  "gaia": {
    "attack": 85.25,
    "speed": 0.8904,
    "singleDps": 76.725,
    "basicDps": 76.725,
    "crowdDps": 254.557
  },
  "elise": {
    "attack": 127.10000000000001,
    "speed": 0.742,
    "singleDps": 131.337,
    "basicDps": 93.207,
    "crowdDps": 351.474
  },
  "vera": {
    "attack": 136.4,
    "speed": 0.6996000000000001,
    "singleDps": 145.948,
    "basicDps": 101.959,
    "crowdDps": 391.891
  },
  "astra": {
    "attack": 154.79999999999998,
    "speed": 0.8692,
    "singleDps": 230.158,
    "basicDps": 203.186,
    "crowdDps": 1533.626
  },
  "solara": {
    "attack": 136.224,
    "speed": 1.2189999999999999,
    "singleDps": 349.19,
    "basicDps": 299.802,
    "crowdDps": 1101.977
  },
  "celestia": {
    "attack": 253.7,
    "speed": 0.636,
    "singleDps": 296.93,
    "basicDps": 215.752,
    "crowdDps": 796.545
  }
};
